export interface Legatum2023 {
  country: string;
  overall: number;
  safety_and_security: number;
  personal_freedom: number;
  governance: number;
  social_capital: number;
  investment_environment: number;
  enterprise_conditions: number;
  infrastructure_and_market_access: number;
  economic_quality: number;
  living_conditions: number;
  health: number;
  education: number;
  natural_environment: number;
}

export const legatum_2023: Legatum2023[] = [
  {
    country: "Denmark",
    overall: 1,
    safety_and_security: 6,
    personal_freedom: 2,
    governance: 3,
    social_capital: 1,
    investment_environment: 8,
    enterprise_conditions: 8,
    infrastructure_and_market_access: 9,
    economic_quality: 7,
    living_conditions: 2,
    health: 16,
    education: 5,
    natural_environment: 5,
  },
  {
    country: "Sweden",
    overall: 2,
    safety_and_security: 10,
    personal_freedom: 4,
    governance: 7,
    social_capital: 4,
    investment_environment: 6,
    enterprise_conditions: 15,
    infrastructure_and_market_access: 7,
    economic_quality: 8,
    living_conditions: 3,
    health: 9,
    education: 8,
    natural_environment: 1,
  },
  {
    country: "Norway",
    overall: 3,
    safety_and_security: 3,
    personal_freedom: 1,
    governance: 2,
    social_capital: 3,
    investment_environment: 9,
    enterprise_conditions: 14,
    infrastructure_and_market_access: 20,
    economic_quality: 5,
    living_conditions: 4,
    health: 7,
    education: 10,
    natural_environment: 9,
  },
  {
    country: "Finland",
    overall: 4,
    safety_and_security: 15,
    personal_freedom: 3,
    governance: 1,
    social_capital: 7,
    investment_environment: 2,
    enterprise_conditions: 12,
    infrastructure_and_market_access: 10,
    economic_quality: 20,
    living_conditions: 7,
    health: 15,
    education: 2,
    natural_environment: 2,
  },
  {
    country: "Switzerland",
    overall: 5,
    safety_and_security: 2,
    personal_freedom: 12,
    governance: 4,
    social_capital: 12,
    investment_environment: 12,
    enterprise_conditions: 1,
    infrastructure_and_market_access: 11,
    economic_quality: 2,
    living_conditions: 5,
    health: 10,
    education: 4,
    natural_environment: 6,
  },
  {
    country: "Netherlands",
    overall: 6,
    safety_and_security: 9,
    personal_freedom: 5,
    governance: 5,
    social_capital: 8,
    investment_environment: 3,
    enterprise_conditions: 9,
    infrastructure_and_market_access: 3,
    economic_quality: 10,
    living_conditions: 1,
    health: 11,
    education: 6,
    natural_environment: 39,
  },
  {
    country: "Luxembourg",
    overall: 7,
    safety_and_security: 1,
    personal_freedom: 6,
    governance: 8,
    social_capital: 18,
    investment_environment: 20,
    enterprise_conditions: 4,
    infrastructure_and_market_access: 6,
    economic_quality: 6,
    living_conditions: 6,
    health: 12,
    education: 36,
    natural_environment: 10,
  },
  {
    country: "Iceland",
    overall: 8,
    safety_and_security: 8,
    personal_freedom: 7,
    governance: 10,
    social_capital: 5,
    investment_environment: 19,
    enterprise_conditions: 20,
    infrastructure_and_market_access: 19,
    economic_quality: 21,
    living_conditions: 10,
    health: 8,
    education: 11,
    natural_environment: 13,
  },
  {
    country: "Germany",
    overall: 9,
    safety_and_security: 19,
    personal_freedom: 9,
    governance: 9,
    social_capital: 20,
    investment_environment: 21,
    enterprise_conditions: 6,
    infrastructure_and_market_access: 5,
    economic_quality: 11,
    living_conditions: 8,
    health: 13,
    education: 19,
    natural_environment: 12,
  },
  {
    country: "New Zealand",
    overall: 10,
    safety_and_security: 32,
    personal_freedom: 11,
    governance: 6,
    social_capital: 2,
    investment_environment: 7,
    enterprise_conditions: 21,
    infrastructure_and_market_access: 23,
    economic_quality: 22,
    living_conditions: 30,
    health: 25,
    education: 18,
    natural_environment: 11,
  },
  {
    country: "Ireland",
    overall: 11,
    safety_and_security: 11,
    personal_freedom: 8,
    governance: 13,
    social_capital: 16,
    investment_environment: 14,
    enterprise_conditions: 16,
    infrastructure_and_market_access: 24,
    economic_quality: 4,
    living_conditions: 19,
    health: 23,
    education: 12,
    natural_environment: 17,
  },
  {
    country: "United Kingdom",
    overall: 12,
    safety_and_security: 21,
    personal_freedom: 17,
    governance: 15,
    social_capital: 15,
    investment_environment: 10,
    enterprise_conditions: 10,
    infrastructure_and_market_access: 12,
    economic_quality: 15,
    living_conditions: 9,
    health: 34,
    education: 14,
    natural_environment: 22,
  },
  {
    country: "Canada",
    overall: 13,
    safety_and_security: 18,
    personal_freedom: 14,
    governance: 12,
    social_capital: 10,
    investment_environment: 13,
    enterprise_conditions: 13,
    infrastructure_and_market_access: 15,
    economic_quality: 32,
    living_conditions: 13,
    health: 32,
    education: 17,
    natural_environment: 20,
  },
  {
    country: "Austria",
    overall: 14,
    safety_and_security: 12,
    personal_freedom: 15,
    governance: 14,
    social_capital: 14,
    investment_environment: 16,
    enterprise_conditions: 19,
    infrastructure_and_market_access: 14,
    economic_quality: 25,
    living_conditions: 21,
    health: 22,
    education: 22,
    natural_environment: 7,
  },
  {
    country: "Australia",
    overall: 15,
    safety_and_security: 20,
    personal_freedom: 20,
    governance: 11,
    social_capital: 6,
    investment_environment: 22,
    enterprise_conditions: 24,
    infrastructure_and_market_access: 28,
    economic_quality: 23,
    living_conditions: 15,
    health: 21,
    education: 7,
    natural_environment: 19,
  },
  {
    country: "Japan",
    overall: 16,
    safety_and_security: 5,
    personal_freedom: 27,
    governance: 17,
    social_capital: 141,
    investment_environment: 5,
    enterprise_conditions: 5,
    infrastructure_and_market_access: 8,
    economic_quality: 28,
    living_conditions: 17,
    health: 2,
    education: 13,
    natural_environment: 15,
  },
  {
    country: "Singapore",
    overall: 17,
    safety_and_security: 7,
    personal_freedom: 107,
    governance: 18,
    social_capital: 21,
    investment_environment: 4,
    enterprise_conditions: 11,
    infrastructure_and_market_access: 1,
    economic_quality: 1,
    living_conditions: 14,
    health: 1,
    education: 1,
    natural_environment: 87,
  },
  {
    country: "Belgium",
    overall: 18,
    safety_and_security: 30,
    personal_freedom: 10,
    governance: 16,
    social_capital: 23,
    investment_environment: 11,
    enterprise_conditions: 25,
    infrastructure_and_market_access: 17,
    economic_quality: 27,
    living_conditions: 18,
    health: 18,
    education: 15,
    natural_environment: 35,
  },
  {
    country: "United States",
    overall: 19,
    safety_and_security: 69,
    personal_freedom: 29,
    governance: 23,
    social_capital: 9,
    investment_environment: 17,
    enterprise_conditions: 3,
    infrastructure_and_market_access: 4,
    economic_quality: 16,
    living_conditions: 29,
    health: 69,
    education: 20,
    natural_environment: 28,
  },
  {
    country: "Taiwan",
    overall: 20,
    safety_and_security: 4,
    personal_freedom: 26,
    governance: 20,
    social_capital: 44,
    investment_environment: 23,
    enterprise_conditions: 7,
    infrastructure_and_market_access: 34,
    economic_quality: 12,
    living_conditions: 31,
    health: 4,
    education: 16,
    natural_environment: 73,
  },
  {
    country: "Estonia",
    overall: 21,
    safety_and_security: 28,
    personal_freedom: 13,
    governance: 19,
    social_capital: 34,
    investment_environment: 28,
    enterprise_conditions: 23,
    infrastructure_and_market_access: 32,
    economic_quality: 14,
    living_conditions: 22,
    health: 37,
    education: 21,
    natural_environment: 8,
  },
  {
    country: "Hong Kong",
    overall: 22,
    safety_and_security: 16,
    personal_freedom: 98,
    governance: 28,
    social_capital: 68,
    investment_environment: 1,
    enterprise_conditions: 2,
    infrastructure_and_market_access: 2,
    economic_quality: 3,
    living_conditions: 27,
    health: 14,
    education: 9,
    natural_environment: 30,
  },
  {
    country: "France",
    overall: 23,
    safety_and_security: 38,
    personal_freedom: 28,
    governance: 21,
    social_capital: 43,
    investment_environment: 18,
    enterprise_conditions: 18,
    infrastructure_and_market_access: 16,
    economic_quality: 30,
    living_conditions: 20,
    health: 20,
    education: 28,
    natural_environment: 14,
  },
  {
    country: "Spain",
    overall: 24,
    safety_and_security: 24,
    personal_freedom: 21,
    governance: 27,
    social_capital: 11,
    investment_environment: 24,
    enterprise_conditions: 27,
    infrastructure_and_market_access: 13,
    economic_quality: 52,
    living_conditions: 11,
    health: 26,
    education: 30,
    natural_environment: 34,
  },
  {
    country: "Czech Republic",
    overall: 25,
    safety_and_security: 13,
    personal_freedom: 22,
    governance: 32,
    social_capital: 36,
    investment_environment: 26,
    enterprise_conditions: 42,
    infrastructure_and_market_access: 40,
    economic_quality: 17,
    living_conditions: 24,
    health: 28,
    education: 31,
    natural_environment: 27,
  },
  {
    country: "Portugal",
    overall: 26,
    safety_and_security: 29,
    personal_freedom: 16,
    governance: 24,
    social_capital: 29,
    investment_environment: 29,
    enterprise_conditions: 31,
    infrastructure_and_market_access: 18,
    economic_quality: 46,
    living_conditions: 23,
    health: 40,
    education: 39,
    natural_environment: 32,
  },
  {
    country: "Slovenia",
    overall: 27,
    safety_and_security: 14,
    personal_freedom: 35,
    governance: 37,
    social_capital: 30,
    investment_environment: 30,
    enterprise_conditions: 33,
    infrastructure_and_market_access: 29,
    economic_quality: 35,
    living_conditions: 28,
    health: 24,
    education: 25,
    natural_environment: 4,
  },
  {
    country: "Malta",
    overall: 28,
    safety_and_security: 17,
    personal_freedom: 24,
    governance: 29,
    social_capital: 13,
    investment_environment: 38,
    enterprise_conditions: 30,
    infrastructure_and_market_access: 38,
    economic_quality: 18,
    living_conditions: 16,
    health: 19,
    education: 38,
    natural_environment: 104,
  },
  {
    country: "South Korea",
    overall: 29,
    safety_and_security: 37,
    personal_freedom: 42,
    governance: 30,
    social_capital: 107,
    investment_environment: 25,
    enterprise_conditions: 37,
    infrastructure_and_market_access: 21,
    economic_quality: 9,
    living_conditions: 26,
    health: 3,
    education: 3,
    natural_environment: 63,
  },
  {
    country: "Italy",
    overall: 30,
    safety_and_security: 27,
    personal_freedom: 31,
    governance: 39,
    social_capital: 41,
    investment_environment: 31,
    enterprise_conditions: 28,
    infrastructure_and_market_access: 25,
    economic_quality: 54,
    living_conditions: 25,
    health: 17,
    education: 32,
    natural_environment: 31,
  },
  {
    country: "Latvia",
    overall: 31,
    safety_and_security: 31,
    personal_freedom: 23,
    governance: 31,
    social_capital: 79,
    investment_environment: 39,
    enterprise_conditions: 36,
    infrastructure_and_market_access: 41,
    economic_quality: 33,
    living_conditions: 39,
    health: 59,
    education: 27,
    natural_environment: 3,
  },
  {
    country: "Lithuania",
    overall: 32,
    safety_and_security: 25,
    personal_freedom: 25,
    governance: 26,
    social_capital: 129,
    investment_environment: 33,
    enterprise_conditions: 34,
    infrastructure_and_market_access: 42,
    economic_quality: 31,
    living_conditions: 38,
    health: 61,
    education: 24,
    natural_environment: 16,
  },
  {
    country: "Israel",
    overall: 33,
    safety_and_security: 124,
    personal_freedom: 49,
    governance: 22,
    social_capital: 83,
    investment_environment: 15,
    enterprise_conditions: 17,
    infrastructure_and_market_access: 33,
    economic_quality: 19,
    living_conditions: 12,
    health: 6,
    education: 26,
    natural_environment: 96,
  },
  {
    country: "Cyprus",
    overall: 34,
    safety_and_security: 43,
    personal_freedom: 32,
    governance: 35,
    social_capital: 69,
    investment_environment: 37,
    enterprise_conditions: 32,
    infrastructure_and_market_access: 35,
    economic_quality: 42,
    living_conditions: 32,
    health: 29,
    education: 34,
    natural_environment: 38,
  },
  {
    country: "Slovakia",
    overall: 35,
    safety_and_security: 22,
    personal_freedom: 30,
    governance: 40,
    social_capital: 39,
    investment_environment: 34,
    enterprise_conditions: 59,
    infrastructure_and_market_access: 45,
    economic_quality: 37,
    living_conditions: 35,
    health: 45,
    education: 48,
    natural_environment: 24,
  },
  {
    country: "Chile",
    overall: 36,
    safety_and_security: 77,
    personal_freedom: 33,
    governance: 34,
    social_capital: 48,
    investment_environment: 36,
    enterprise_conditions: 35,
    infrastructure_and_market_access: 27,
    economic_quality: 39,
    living_conditions: 40,
    health: 51,
    education: 44,
    natural_environment: 44,
  },
  {
    country: "Poland",
    overall: 37,
    safety_and_security: 26,
    personal_freedom: 55,
    governance: 48,
    social_capital: 27,
    investment_environment: 42,
    enterprise_conditions: 45,
    infrastructure_and_market_access: 39,
    economic_quality: 36,
    living_conditions: 33,
    health: 48,
    education: 37,
    natural_environment: 43,
  },
  {
    country: "Uruguay",
    overall: 38,
    safety_and_security: 46,
    personal_freedom: 18,
    governance: 25,
    social_capital: 17,
    investment_environment: 40,
    enterprise_conditions: 70,
    infrastructure_and_market_access: 62,
    economic_quality: 60,
    living_conditions: 44,
    health: 35,
    education: 53,
    natural_environment: 52,
  },
  {
    country: "Costa Rica",
    overall: 39,
    safety_and_security: 48,
    personal_freedom: 19,
    governance: 33,
    social_capital: 25,
    investment_environment: 52,
    enterprise_conditions: 46,
    infrastructure_and_market_access: 56,
    economic_quality: 59,
    living_conditions: 58,
    health: 30,
    education: 50,
    natural_environment: 23,
  },
  {
    country: "Greece",
    overall: 40,
    safety_and_security: 34,
    personal_freedom: 40,
    governance: 43,
    social_capital: 101,
    investment_environment: 69,
    enterprise_conditions: 49,
    infrastructure_and_market_access: 26,
    economic_quality: 86,
    living_conditions: 34,
    health: 41,
    education: 33,
    natural_environment: 29,
  },
  {
    country: "Croatia",
    overall: 41,
    safety_and_security: 33,
    personal_freedom: 36,
    governance: 52,
    social_capital: 103,
    investment_environment: 51,
    enterprise_conditions: 88,
    infrastructure_and_market_access: 30,
    economic_quality: 47,
    living_conditions: 36,
    health: 53,
    education: 43,
    natural_environment: 26,
  },
  {
    country: "Hungary",
    overall: 42,
    safety_and_security: 35,
    personal_freedom: 76,
    governance: 92,
    social_capital: 47,
    investment_environment: 45,
    enterprise_conditions: 96,
    infrastructure_and_market_access: 44,
    economic_quality: 29,
    living_conditions: 37,
    health: 46,
    education: 41,
    natural_environment: 36,
  },
  {
    country: "Malasyia",
    overall: 43,
    safety_and_security: 73,
    personal_freedom: 113,
    governance: 50,
    social_capital: 63,
    investment_environment: 27,
    enterprise_conditions: 29,
    infrastructure_and_market_access: 37,
    economic_quality: 34,
    living_conditions: 64,
    health: 42,
    education: 46,
    natural_environment: 46,
  },
  {
    country: "United Arab Emirates",
    overall: 44,
    safety_and_security: 50,
    personal_freedom: 146,
    governance: 38,
    social_capital: 78,
    investment_environment: 32,
    enterprise_conditions: 22,
    infrastructure_and_market_access: 22,
    economic_quality: 26,
    living_conditions: 47,
    health: 33,
    education: 42,
    natural_environment: 119,
  },
  {
    country: "Romania",
    overall: 45,
    safety_and_security: 36,
    personal_freedom: 39,
    governance: 51,
    social_capital: 116,
    investment_environment: 44,
    enterprise_conditions: 80,
    infrastructure_and_market_access: 49,
    economic_quality: 44,
    living_conditions: 54,
    health: 72,
    education: 54,
    natural_environment: 45,
  },
  {
    country: "Qatar",
    overall: 46,
    safety_and_security: 23,
    personal_freedom: 149,
    governance: 47,
    social_capital: 51,
    investment_environment: 43,
    enterprise_conditions: 26,
    infrastructure_and_market_access: 36,
    economic_quality: 13,
    living_conditions: 48,
    health: 38,
    education: 60,
    natural_environment: 134,
  },
  {
    country: "Mauritius",
    overall: 47,
    safety_and_security: 42,
    personal_freedom: 52,
    governance: 36,
    social_capital: 37,
    investment_environment: 41,
    enterprise_conditions: 54,
    infrastructure_and_market_access: 53,
    economic_quality: 72,
    living_conditions: 60,
    health: 81,
    education: 62,
    natural_environment: 120,
  },
  {
    country: "Bulgaria",
    overall: 48,
    safety_and_security: 58,
    personal_freedom: 51,
    governance: 61,
    social_capital: 81,
    investment_environment: 53,
    enterprise_conditions: 52,
    infrastructure_and_market_access: 52,
    economic_quality: 43,
    living_conditions: 51,
    health: 65,
    education: 47,
    natural_environment: 64,
  },
  {
    country: "Montenegro",
    overall: 49,
    safety_and_security: 41,
    personal_freedom: 48,
    governance: 55,
    social_capital: 49,
    investment_environment: 72,
    enterprise_conditions: 40,
    infrastructure_and_market_access: 58,
    economic_quality: 69,
    living_conditions: 50,
    health: 103,
    education: 51,
    natural_environment: 100,
  },
  {
    country: "Panama",
    overall: 50,
    safety_and_security: 49,
    personal_freedom: 54,
    governance: 66,
    social_capital: 45,
    investment_environment: 59,
    enterprise_conditions: 84,
    infrastructure_and_market_access: 4,
    economic_quality: 50,
    living_conditions: 79,
    health: 57,
    education: 93,
    natural_environment: 25,
  },
  {
    country: "Seychelles",
    overall: 51,
    safety_and_security: 52,
    personal_freedom: 71,
    governance: 44,
    social_capital: 53,
    investment_environment: 67,
    enterprise_conditions: 61,
    infrastructure_and_market_access: 61,
    economic_quality: 90,
    living_conditions: 63,
    health: 39,
    education: 68,
    natural_environment: 54,
  },
  {
    country: "Serbia",
    overall: 52,
    safety_and_security: 44,
    personal_freedom: 75,
    governance: 96,
    social_capital: 38,
    investment_environment: 78,
    enterprise_conditions: 82,
    infrastructure_and_market_access: 66,
    economic_quality: 61,
    living_conditions: 41,
    health: 80,
    education: 45,
    natural_environment: 131,
  },
  {
    country: "Georgia",
    overall: 53,
    safety_and_security: 82,
    personal_freedom: 59,
    governance: 53,
    social_capital: 104,
    investment_environment: 47,
    enterprise_conditions: 58,
    infrastructure_and_market_access: 55,
    economic_quality: 78,
    living_conditions: 78,
    health: 90,
    education: 49,
    natural_environment: 128,
  },
  {
    country: "China",
    overall: 54,
    safety_and_security: 86,
    personal_freedom: 162,
    governance: 74,
    social_capital: 31,
    investment_environment: 64,
    enterprise_conditions: 38,
    infrastructure_and_market_access: 43,
    economic_quality: 24,
    living_conditions: 46,
    health: 5,
    education: 56,
    natural_environment: 139,
  },
  {
    country: "North Macedonia",
    overall: 55,
    safety_and_security: 55,
    personal_freedom: 60,
    governance: 73,
    social_capital: 77,
    investment_environment: 49,
    enterprise_conditions: 72,
    infrastructure_and_market_access: 73,
    economic_quality: 73,
    living_conditions: 52,
    health: 74,
    education: 88,
    natural_environment: 92,
  },
  {
    country: "Trinidad and Tobago",
    overall: 56,
    safety_and_security: 84,
    personal_freedom: 41,
    governance: 60,
    social_capital: 75,
    investment_environment: 79,
    enterprise_conditions: 98,
    infrastructure_and_market_access: 75,
    economic_quality: 70,
    living_conditions: 55,
    health: 64,
    education: 69,
    natural_environment: 107,
  },
  {
    country: "Jamaica",
    overall: 57,
    safety_and_security: 120,
    personal_freedom: 37,
    governance: 56,
    social_capital: 87,
    investment_environment: 62,
    enterprise_conditions: 51,
    infrastructure_and_market_access: 74,
    economic_quality: 91,
    living_conditions: 71,
    health: 67,
    education: 76,
    natural_environment: 112,
  },
  {
    country: "Argentina",
    overall: 58,
    safety_and_security: 80,
    personal_freedom: 34,
    governance: 67,
    social_capital: 26,
    investment_environment: 87,
    enterprise_conditions: 129,
    infrastructure_and_market_access: 85,
    economic_quality: 118,
    living_conditions: 56,
    health: 60,
    education: 58,
    natural_environment: 49,
  },
  {
    country: "Peru",
    overall: 59,
    safety_and_security: 89,
    personal_freedom: 57,
    governance: 77,
    social_capital: 90,
    investment_environment: 73,
    enterprise_conditions: 69,
    infrastructure_and_market_access: 83,
    economic_quality: 62,
    living_conditions: 99,
    health: 52,
    education: 71,
    natural_environment: 33,
  },
  {
    country: "Kuwait",
    overall: 60,
    safety_and_security: 51,
    personal_freedom: 119,
    governance: 87,
    social_capital: 99,
    investment_environment: 63,
    enterprise_conditions: 76,
    infrastructure_and_market_access: 64,
    economic_quality: 51,
    living_conditions: 42,
    health: 43,
    education: 75,
    natural_environment: 137,
  },
  {
    country: "Armenia",
    overall: 61,
    safety_and_security: 75,
    personal_freedom: 70,
    governance: 64,
    social_capital: 125,
    investment_environment: 75,
    enterprise_conditions: 44,
    infrastructure_and_market_access: 71,
    economic_quality: 83,
    living_conditions: 76,
    health: 68,
    education: 59,
    natural_environment: 99,
  },
  {
    country: "Bahrain",
    overall: 62,
    safety_and_security: 95,
    personal_freedom: 156,
    governance: 98,
    social_capital: 55,
    investment_environment: 35,
    enterprise_conditions: 60,
    infrastructure_and_market_access: 31,
    economic_quality: 56,
    living_conditions: 45,
    health: 50,
    education: 63,
    natural_environment: 142,
  },
  {
    country: "Indonesia",
    overall: 63,
    safety_and_security: 78,
    personal_freedom: 95,
    governance: 57,
    social_capital: 42,
    investment_environment: 65,
    enterprise_conditions: 53,
    infrastructure_and_market_access: 65,
    economic_quality: 58,
    living_conditions: 98,
    health: 87,
    education: 89,
    natural_environment: 77,
  },
  {
    country: "Thailand",
    overall: 64,
    safety_and_security: 117,
    personal_freedom: 118,
    governance: 114,
    social_capital: 28,
    investment_environment: 46,
    enterprise_conditions: 64,
    infrastructure_and_market_access: 51,
    economic_quality: 40,
    living_conditions: 69,
    health: 31,
    education: 72,
    natural_environment: 111,
  },
  {
    country: "Albania",
    overall: 65,
    safety_and_security: 57,
    personal_freedom: 73,
    governance: 75,
    social_capital: 128,
    investment_environment: 76,
    enterprise_conditions: 73,
    infrastructure_and_market_access: 63,
    economic_quality: 101,
    living_conditions: 80,
    health: 66,
    education: 57,
    natural_environment: 57,
  },
  {
    country: "Brazil",
    overall: 66,
    safety_and_security: 119,
    personal_freedom: 67,
    governance: 86,
    social_capital: 35,
    investment_environment: 77,
    enterprise_conditions: 120,
    infrastructure_and_market_access: 87,
    economic_quality: 81,
    living_conditions: 57,
    health: 83,
    education: 91,
    natural_environment: 18,
  },
  {
    country: "Oman",
    overall: 67,
    safety_and_security: 40,
    personal_freedom: 142,
    governance: 83,
    social_capital: 88,
    investment_environment: 58,
    enterprise_conditions: 48,
    infrastructure_and_market_access: 48,
    economic_quality: 63,
    living_conditions: 67,
    health: 55,
    education: 83,
    natural_environment: 153,
  },
  {
    country: "Dominican Republic",
    overall: 68,
    safety_and_security: 108,
    personal_freedom: 46,
    governance: 90,
    social_capital: 50,
    investment_environment: 81,
    enterprise_conditions: 79,
    infrastructure_and_market_access: 69,
    economic_quality: 66,
    living_conditions: 88,
    health: 89,
    education: 99,
    natural_environment: 55,
  },
  {
    country: "Kazakhstan",
    overall: 69,
    safety_and_security: 81,
    personal_freedom: 126,
    governance: 99,
    social_capital: 108,
    investment_environment: 74,
    enterprise_conditions: 83,
    infrastructure_and_market_access: 91,
    economic_quality: 38,
    living_conditions: 53,
    health: 77,
    education: 35,
    natural_environment: 126,
  },
  {
    country: "Moldova",
    overall: 70,
    safety_and_security: 67,
    personal_freedom: 66,
    governance: 79,
    social_capital: 72,
    investment_environment: 84,
    enterprise_conditions: 114,
    infrastructure_and_market_access: 92,
    economic_quality: 93,
    living_conditions: 62,
    health: 93,
    education: 52,
    natural_environment: 115,
  },
  {
    country: "Mexico",
    overall: 71,
    safety_and_security: 148,
    personal_freedom: 80,
    governance: 101,
    social_capital: 61,
    investment_environment: 66,
    enterprise_conditions: 81,
    infrastructure_and_market_access: 47,
    economic_quality: 49,
    living_conditions: 86,
    health: 71,
    education: 77,
    natural_environment: 60,
  },
  {
    country: "Bosnia and Herzegovina",
    overall: 72,
    safety_and_security: 47,
    personal_freedom: 69,
    governance: 122,
    social_capital: 80,
    investment_environment: 83,
    enterprise_conditions: 116,
    infrastructure_and_market_access: 80,
    economic_quality: 75,
    living_conditions: 49,
    health: 95,
    education: 84,
    natural_environment: 135,
  },
  {
    country: "Vietnam",
    overall: 73,
    safety_and_security: 83,
    personal_freedom: 139,
    governance: 80,
    social_capital: 19,
    investment_environment: 105,
    enterprise_conditions: 89,
    infrastructure_and_market_access: 5,
    economic_quality: 48,
    living_conditions: 92,
    health: 44,
    education: 67,
    natural_environment: 114,
  },
  {
    country: "Ukraine",
    overall: 74,
    safety_and_security: 131,
    personal_freedom: 68,
    governance: 91,
    social_capital: 59,
    investment_environment: 124,
    enterprise_conditions: 78,
    infrastructure_and_market_access: 76,
    economic_quality: 77,
    living_conditions: 74,
    health: 101,
    education: 40,
    natural_environment: 88,
  },
  {
    country: "South Africa",
    overall: 75,
    safety_and_security: 136,
    personal_freedom: 38,
    governance: 49,
    social_capital: 40,
    investment_environment: 48,
    enterprise_conditions: 63,
    infrastructure_and_market_access: 68,
    economic_quality: 74,
    living_conditions: 102,
    health: 129,
    education: 102,
    natural_environment: 140,
  },
  {
    country: "Paraguay",
    overall: 76,
    safety_and_security: 64,
    personal_freedom: 74,
    governance: 103,
    social_capital: 32,
    investment_environment: 89,
    enterprise_conditions: 119,
    infrastructure_and_market_access: 89,
    economic_quality: 84,
    living_conditions: 82,
    health: 88,
    education: 103,
    natural_environment: 37,
  },
  {
    country: "Russia",
    overall: 77,
    safety_and_security: 139,
    personal_freedom: 140,
    governance: 111,
    social_capital: 54,
    investment_environment: 85,
    enterprise_conditions: 97,
    infrastructure_and_market_access: 60,
    economic_quality: 41,
    living_conditions: 68,
    health: 84,
    education: 23,
    natural_environment: 76,
  },
  {
    country: "Belarus",
    overall: 78,
    safety_and_security: 72,
    personal_freedom: 143,
    governance: 136,
    social_capital: 134,
    investment_environment: 103,
    enterprise_conditions: 117,
    infrastructure_and_market_access: 79,
    economic_quality: 45,
    living_conditions: 43,
    health: 62,
    education: 29,
    natural_environment: 42,
  },
  {
    country: "Saudi Arabia",
    overall: 79,
    safety_and_security: 98,
    personal_freedom: 163,
    governance: 82,
    social_capital: 105,
    investment_environment: 56,
    enterprise_conditions: 43,
    infrastructure_and_market_access: 54,
    economic_quality: 55,
    living_conditions: 75,
    health: 56,
    education: 64,
    natural_environment: 138,
  },
  {
    country: "Cape Verde",
    overall: 80,
    safety_and_security: 39,
    personal_freedom: 43,
    governance: 42,
    social_capital: 94,
    investment_environment: 109,
    enterprise_conditions: 99,
    infrastructure_and_market_access: 118,
    economic_quality: 127,
    living_conditions: 100,
    health: 73,
    education: 101,
    natural_environment: 80,
  },
  {
    country: "Colombia",
    overall: 81,
    safety_and_security: 156,
    personal_freedom: 82,
    governance: 88,
    social_capital: 62,
    investment_environment: 61,
    enterprise_conditions: 93,
    infrastructure_and_market_access: 70,
    economic_quality: 85,
    living_conditions: 89,
    health: 36,
    education: 80,
    natural_environment: 40,
  },
  {
    country: "Suriname",
    overall: 82,
    safety_and_security: 63,
    personal_freedom: 47,
    governance: 81,
    social_capital: 95,
    investment_environment: 120,
    enterprise_conditions: 115,
    infrastructure_and_market_access: 93,
    economic_quality: 108,
    living_conditions: 72,
    health: 123,
    education: 97,
    natural_environment: 21,
  },
  {
    country: "Botswana",
    overall: 83,
    safety_and_security: 70,
    personal_freedom: 56,
    governance: 41,
    social_capital: 118,
    investment_environment: 60,
    enterprise_conditions: 68,
    infrastructure_and_market_access: 95,
    economic_quality: 57,
    living_conditions: 114,
    health: 131,
    education: 100,
    natural_environment: 143,
  },
  {
    country: "Philippines",
    overall: 84,
    safety_and_security: 146,
    personal_freedom: 83,
    governance: 93,
    social_capital: 22,
    investment_environment: 82,
    enterprise_conditions: 71,
    infrastructure_and_market_access: 78,
    economic_quality: 53,
    living_conditions: 109,
    health: 96,
    education: 86,
    natural_environment: 71,
  },
  {
    country: "Ecuador",
    overall: 85,
    safety_and_security: 88,
    personal_freedom: 64,
    governance: 105,
    social_capital: 66,
    investment_environment: 100,
    enterprise_conditions: 118,
    infrastructure_and_market_access: 81,
    economic_quality: 114,
    living_conditions: 97,
    health: 82,
    education: 82,
    natural_environment: 51,
  },
  {
    country: "Jordan",
    overall: 86,
    safety_and_security: 74,
    personal_freedom: 116,
    governance: 68,
    social_capital: 152,
    investment_environment: 50,
    enterprise_conditions: 41,
    infrastructure_and_market_access: 67,
    economic_quality: 121,
    living_conditions: 61,
    health: 100,
    education: 90,
    natural_environment: 146,
  },
  {
    country: "Sao Tome and Principe",
    overall: 87,
    safety_and_security: 45,
    personal_freedom: 45,
    governance: 62,
    social_capital: 97,
    investment_environment: 88,
    enterprise_conditions: 75,
    infrastructure_and_market_access: 122,
    economic_quality: 82,
    living_conditions: 112,
    health: 94,
    education: 110,
    natural_environment: 91,
  },
  {
    country: "Mongolia",
    overall: 88,
    safety_and_security: 61,
    personal_freedom: 58,
    governance: 70,
    social_capital: 57,
    investment_environment: 111,
    enterprise_conditions: 111,
    infrastructure_and_market_access: 113,
    economic_quality: 80,
    living_conditions: 107,
    health: 110,
    education: 61,
    natural_environment: 148,
  },
  {
    country: "Guyana",
    overall: 89,
    safety_and_security: 96,
    personal_freedom: 61,
    governance: 71,
    social_capital: 96,
    investment_environment: 101,
    enterprise_conditions: 113,
    infrastructure_and_market_access: 109,
    economic_quality: 64,
    living_conditions: 85,
    health: 120,
    education: 96,
    natural_environment: 47,
  },
  {
    country: "Namibia",
    overall: 90,
    safety_and_security: 65,
    personal_freedom: 53,
    governance: 46,
    social_capital: 92,
    investment_environment: 80,
    enterprise_conditions: 55,
    infrastructure_and_market_access: 100,
    economic_quality: 133,
    living_conditions: 122,
    health: 125,
    education: 109,
    natural_environment: 98,
  },
  {
    country: "Sri Lanka",
    overall: 91,
    safety_and_security: 134,
    personal_freedom: 96,
    governance: 78,
    social_capital: 71,
    investment_environment: 90,
    enterprise_conditions: 74,
    infrastructure_and_market_access: 97,
    economic_quality: 128,
    living_conditions: 104,
    health: 47,
    education: 70,
    natural_environment: 58,
  },
  {
    country: "Azerbaijan",
    overall: 92,
    safety_and_security: 111,
    personal_freedom: 144,
    governance: 113,
    social_capital: 132,
    investment_environment: 54,
    enterprise_conditions: 47,
    infrastructure_and_market_access: 72,
    economic_quality: 65,
    living_conditions: 65,
    health: 85,
    education: 79,
    natural_environment: 149,
  },
  {
    country: "Belize",
    overall: 93,
    safety_and_security: 90,
    personal_freedom: 44,
    governance: 97,
    social_capital: 117,
    investment_environment: 113,
    enterprise_conditions: 110,
    infrastructure_and_market_access: 98,
    economic_quality: 123,
    living_conditions: 91,
    health: 91,
    education: 104,
    natural_environment: 53,
  },
  {
    country: "Kyrgyzstan",
    overall: 94,
    safety_and_security: 71,
    personal_freedom: 103,
    governance: 108,
    social_capital: 100,
    investment_environment: 99,
    enterprise_conditions: 124,
    infrastructure_and_market_access: 110,
    economic_quality: 88,
    living_conditions: 84,
    health: 76,
    education: 85,
    natural_environment: 95,
  },
  {
    country: "Turkey",
    overall: 95,
    safety_and_security: 147,
    personal_freedom: 152,
    governance: 128,
    social_capital: 137,
    investment_environment: 68,
    enterprise_conditions: 65,
    infrastructure_and_market_access: 50,
    economic_quality: 71,
    living_conditions: 59,
    health: 63,
    education: 74,
    natural_environment: 86,
  },
  {
    country: "Morocco",
    overall: 96,
    safety_and_security: 62,
    personal_freedom: 114,
    governance: 89,
    social_capital: 162,
    investment_environment: 55,
    enterprise_conditions: 90,
    infrastructure_and_market_access: 57,
    economic_quality: 95,
    living_conditions: 95,
    health: 86,
    education: 122,
    natural_environment: 132,
  },
  {
    country: "El Salvador",
    overall: 97,
    safety_and_security: 125,
    personal_freedom: 88,
    governance: 102,
    social_capital: 85,
    investment_environment: 92,
    enterprise_conditions: 94,
    infrastructure_and_market_access: 77,
    economic_quality: 107,
    living_conditions: 90,
    health: 98,
    education: 108,
    natural_environment: 121,
  },
  {
    country: "Ghana",
    overall: 98,
    safety_and_security: 79,
    personal_freedom: 50,
    governance: 58,
    social_capital: 114,
    investment_environment: 98,
    enterprise_conditions: 50,
    infrastructure_and_market_access: 114,
    economic_quality: 134,
    living_conditions: 115,
    health: 119,
    education: 118,
    natural_environment: 106,
  },
  {
    country: "Tunisia",
    overall: 99,
    safety_and_security: 122,
    personal_freedom: 86,
    governance: 63,
    social_capital: 156,
    investment_environment: 95,
    enterprise_conditions: 105,
    infrastructure_and_market_access: 94,
    economic_quality: 111,
    living_conditions: 73,
    health: 79,
    education: 95,
    natural_environment: 147,
  },
  {
    country: "Uzbekistan",
    overall: 100,
    safety_and_security: 53,
    personal_freedom: 147,
    governance: 123,
    social_capital: 46,
    investment_environment: 107,
    enterprise_conditions: 121,
    infrastructure_and_market_access: 104,
    economic_quality: 79,
    living_conditions: 103,
    health: 49,
    education: 73,
    natural_environment: 162,
  },
  {
    country: "Guatemala",
    overall: 101,
    safety_and_security: 116,
    personal_freedom: 91,
    governance: 125,
    social_capital: 91,
    investment_environment: 93,
    enterprise_conditions: 85,
    infrastructure_and_market_access: 86,
    economic_quality: 76,
    living_conditions: 113,
    health: 104,
    education: 124,
    natural_environment: 81,
  },
  {
    country: "Senegal",
    overall: 102,
    safety_and_security: 104,
    personal_freedom: 62,
    governance: 59,
    social_capital: 65,
    investment_environment: 102,
    enterprise_conditions: 56,
    infrastructure_and_market_access: 116,
    economic_quality: 122,
    living_conditions: 117,
    health: 117,
    education: 148,
    natural_environment: 75,
  },
  {
    country: "India",
    overall: 103,
    safety_and_security: 138,
    personal_freedom: 112,
    governance: 54,
    social_capital: 124,
    investment_environment: 70,
    enterprise_conditions: 39,
    infrastructure_and_market_access: 84,
    economic_quality: 89,
    living_conditions: 125,
    health: 112,
    education: 106,
    natural_environment: 161,
  },
  {
    country: "Cuba",
    overall: 104,
    safety_and_security: 103,
    personal_freedom: 155,
    governance: 131,
    social_capital: 33,
    investment_environment: 116,
    enterprise_conditions: 159,
    infrastructure_and_market_access: 105,
    economic_quality: 131,
    living_conditions: 77,
    health: 27,
    education: 55,
    natural_environment: 83,
  },
  {
    country: "Honduras",
    overall: 105,
    safety_and_security: 129,
    personal_freedom: 94,
    governance: 141,
    social_capital: 56,
    investment_environment: 91,
    enterprise_conditions: 100,
    infrastructure_and_market_access: 88,
    economic_quality: 100,
    living_conditions: 111,
    health: 99,
    education: 117,
    natural_environment: 65,
  },
  {
    country: "Bolivia",
    overall: 106,
    safety_and_security: 99,
    personal_freedom: 79,
    governance: 127,
    social_capital: 74,
    investment_environment: 112,
    enterprise_conditions: 154,
    infrastructure_and_market_access: 111,
    economic_quality: 139,
    living_conditions: 101,
    health: 113,
    education: 94,
    natural_environment: 48,
  },
  {
    country: "Turkmenistan",
    overall: 107,
    safety_and_security: 66,
    personal_freedom: 161,
    governance: 156,
    social_capital: 24,
    investment_environment: 121,
    enterprise_conditions: 153,
    infrastructure_and_market_access: 121,
    economic_quality: 67,
    living_conditions: 66,
    health: 54,
    education: 66,
    natural_environment: 159,
  },
  {
    country: "Kenya",
    overall: 108,
    safety_and_security: 144,
    personal_freedom: 92,
    governance: 84,
    social_capital: 67,
    investment_environment: 71,
    enterprise_conditions: 66,
    infrastructure_and_market_access: 108,
    economic_quality: 98,
    living_conditions: 131,
    health: 114,
    education: 113,
    natural_environment: 122,
  },
  {
    country: "Algeria",
    overall: 109,
    safety_and_security: 60,
    personal_freedom: 128,
    governance: 107,
    social_capital: 155,
    investment_environment: 131,
    enterprise_conditions: 138,
    infrastructure_and_market_access: 99,
    economic_quality: 132,
    living_conditions: 70,
    health: 70,
    education: 92,
    natural_environment: 144,
  },
  {
    country: "Nepal",
    overall: 110,
    safety_and_security: 94,
    personal_freedom: 84,
    governance: 72,
    social_capital: 73,
    investment_environment: 117,
    enterprise_conditions: 112,
    infrastructure_and_market_access: 130,
    economic_quality: 102,
    living_conditions: 123,
    health: 118,
    education: 119,
    natural_environment: 133,
  },
  {
    country: "Rwanda",
    overall: 111,
    safety_and_security: 126,
    personal_freedom: 115,
    governance: 45,
    social_capital: 139,
    investment_environment: 57,
    enterprise_conditions: 57,
    infrastructure_and_market_access: 115,
    economic_quality: 87,
    living_conditions: 147,
    health: 116,
    education: 133,
    natural_environment: 109,
  },
  {
    country: "Lebanon",
    overall: 112,
    safety_and_security: 128,
    personal_freedom: 100,
    governance: 143,
    social_capital: 165,
    investment_environment: 104,
    enterprise_conditions: 104,
    infrastructure_and_market_access: 101,
    economic_quality: 161,
    living_conditions: 83,
    health: 102,
    education: 65,
    natural_environment: 116,
  },
  {
    country: "Tajikistan",
    overall: 113,
    safety_and_security: 76,
    personal_freedom: 145,
    governance: 129,
    social_capital: 52,
    investment_environment: 122,
    enterprise_conditions: 135,
    infrastructure_and_market_access: 125,
    economic_quality: 109,
    living_conditions: 105,
    health: 75,
    education: 81,
    natural_environment: 150,
  },
  {
    country: "Nicaragua",
    overall: 114,
    safety_and_security: 109,
    personal_freedom: 124,
    governance: 153,
    social_capital: 70,
    investment_environment: 125,
    enterprise_conditions: 146,
    infrastructure_and_market_access: 103,
    economic_quality: 116,
    living_conditions: 110,
    health: 78,
    education: 120,
    natural_environment: 67,
  },
  {
    country: "Laos",
    overall: 115,
    safety_and_security: 56,
    personal_freedom: 157,
    governance: 119,
    social_capital: 136,
    investment_environment: 145,
    enterprise_conditions: 101,
    infrastructure_and_market_access: 90,
    economic_quality: 97,
    living_conditions: 120,
    health: 111,
    education: 111,
    natural_environment: 72,
  },
  {
    country: "Gambia",
    overall: 116,
    safety_and_security: 92,
    personal_freedom: 102,
    governance: 65,
    social_capital: 64,
    investment_environment: 108,
    enterprise_conditions: 67,
    infrastructure_and_market_access: 135,
    economic_quality: 150,
    living_conditions: 129,
    health: 139,
    education: 142,
    natural_environment: 82,
  },
  {
    country: "Tanzania",
    overall: 117,
    safety_and_security: 105,
    personal_freedom: 111,
    governance: 85,
    social_capital: 133,
    investment_environment: 119,
    enterprise_conditions: 103,
    infrastructure_and_market_access: 131,
    economic_quality: 96,
    living_conditions: 137,
    health: 128,
    education: 130,
    natural_environment: 70,
  },
  {
    country: "Cambodia",
    overall: 118,
    safety_and_security: 100,
    personal_freedom: 137,
    governance: 157,
    social_capital: 140,
    investment_environment: 126,
    enterprise_conditions: 133,
    infrastructure_and_market_access: 96,
    economic_quality: 68,
    living_conditions: 127,
    health: 92,
    education: 127,
    natural_environment: 78,
  },
  {
    country: "Gabon",
    overall: 119,
    safety_and_security: 106,
    personal_freedom: 108,
    governance: 139,
    social_capital: 110,
    investment_environment: 141,
    enterprise_conditions: 148,
    infrastructure_and_market_access: 126,
    economic_quality: 113,
    living_conditions: 108,
    health: 140,
    education: 107,
    natural_environment: 90,
  },
  {
    country: "Ivory Coast",
    overall: 120,
    safety_and_security: 118,
    personal_freedom: 93,
    governance: 100,
    social_capital: 144,
    investment_environment: 115,
    enterprise_conditions: 107,
    infrastructure_and_market_access: 123,
    economic_quality: 92,
    living_conditions: 128,
    health: 151,
    education: 138,
    natural_environment: 89,
  },
  {
    country: "Egypt",
    overall: 121,
    safety_and_security: 142,
    personal_freedom: 160,
    governance: 140,
    social_capital: 161,
    investment_environment: 86,
    enterprise_conditions: 62,
    infrastructure_and_market_access: 82,
    economic_quality: 136,
    living_conditions: 93,
    health: 107,
    education: 105,
    natural_environment: 156,
  },
  {
    country: "Djibouti",
    overall: 122,
    safety_and_security: 85,
    personal_freedom: 130,
    governance: 115,
    social_capital: 142,
    investment_environment: 97,
    enterprise_conditions: 109,
    infrastructure_and_market_access: 112,
    economic_quality: 104,
    living_conditions: 118,
    health: 126,
    education: 132,
    natural_environment: 154,
  },
  {
    country: "Benin",
    overall: 123,
    safety_and_security: 68,
    personal_freedom: 78,
    governance: 69,
    social_capital: 159,
    investment_environment: 130,
    enterprise_conditions: 77,
    infrastructure_and_market_access: 137,
    economic_quality: 110,
    living_conditions: 143,
    health: 147,
    education: 139,
    natural_environment: 123,
  },
  {
    country: "Bangladesh",
    overall: 124,
    safety_and_security: 141,
    personal_freedom: 125,
    governance: 133,
    social_capital: 112,
    investment_environment: 133,
    enterprise_conditions: 91,
    infrastructure_and_market_access: 106,
    economic_quality: 103,
    living_conditions: 121,
    health: 106,
    education: 126,
    natural_environment: 151,
  },
  {
    country: "Malawi",
    overall: 125,
    safety_and_security: 102,
    personal_freedom: 72,
    governance: 76,
    social_capital: 153,
    investment_environment: 114,
    enterprise_conditions: 95,
    infrastructure_and_market_access: 141,
    economic_quality: 147,
    living_conditions: 155,
    health: 121,
    education: 145,
    natural_environment: 66,
  },
  {
    country: "Iran",
    overall: 126,
    safety_and_security: 130,
    personal_freedom: 165,
    governance: 146,
    social_capital: 122,
    investment_environment: 129,
    enterprise_conditions: 162,
    infrastructure_and_market_access: 102,
    economic_quality: 138,
    living_conditions: 81,
    health: 58,
    education: 78,
    natural_environment: 158,
  },
  {
    country: "Zambia",
    overall: 127,
    safety_and_security: 101,
    personal_freedom: 109,
    governance: 106,
    social_capital: 113,
    investment_environment: 110,
    enterprise_conditions: 87,
    infrastructure_and_market_access: 143,
    economic_quality: 162,
    living_conditions: 150,
    health: 137,
    education: 134,
    natural_environment: 59,
  },
  {
    country: "Comoros",
    overall: 128,
    safety_and_security: 59,
    personal_freedom: 97,
    governance: 150,
    social_capital: 82,
    investment_environment: 139,
    enterprise_conditions: 137,
    infrastructure_and_market_access: 145,
    economic_quality: 155,
    living_conditions: 134,
    health: 130,
    education: 135,
    natural_environment: 74,
  },
  {
    country: "Uganda",
    overall: 129,
    safety_and_security: 135,
    personal_freedom: 121,
    governance: 124,
    social_capital: 109,
    investment_environment: 94,
    enterprise_conditions: 86,
    infrastructure_and_market_access: 127,
    economic_quality: 117,
    living_conditions: 140,
    health: 133,
    education: 137,
    natural_environment: 113,
  },
  {
    country: "Papua New Guinea",
    overall: 130,
    safety_and_security: 113,
    personal_freedom: 63,
    governance: 112,
    social_capital: 89,
    investment_environment: 142,
    enterprise_conditions: 132,
    infrastructure_and_market_access: 144,
    economic_quality: 126,
    living_conditions: 158,
    health: 149,
    education: 141,
    natural_environment: 62,
  },
  {
    country: "Equatorial Guinea",
    overall: 131,
    safety_and_security: 91,
    personal_freedom: 151,
    governance: 152,
    social_capital: 93,
    investment_environment: 118,
    enterprise_conditions: 150,
    infrastructure_and_market_access: 129,
    economic_quality: 94,
    living_conditions: 116,
    health: 156,
    education: 129,
    natural_environment: 56,
  },
  {
    country: "Lesotho",
    overall: 132,
    safety_and_security: 97,
    personal_freedom: 77,
    governance: 95,
    social_capital: 130,
    investment_environment: 132,
    enterprise_conditions: 136,
    infrastructure_and_market_access: 133,
    economic_quality: 137,
    living_conditions: 142,
    health: 164,
    education: 123,
    natural_environment: 165,
  },
  {
    country: "Togo",
    overall: 133,
    safety_and_security: 93,
    personal_freedom: 105,
    governance: 126,
    social_capital: 145,
    investment_environment: 135,
    enterprise_conditions: 122,
    infrastructure_and_market_access: 148,
    economic_quality: 140,
    living_conditions: 141,
    health: 142,
    education: 131,
    natural_environment: 127,
  },
  {
    country: "Eswatini",
    overall: 134,
    safety_and_security: 114,
    personal_freedom: 150,
    governance: 134,
    social_capital: 148,
    investment_environment: 106,
    enterprise_conditions: 123,
    infrastructure_and_market_access: 120,
    economic_quality: 106,
    living_conditions: 126,
    health: 161,
    education: 125,
    natural_environment: 145,
  },
  {
    country: "Burkina Faso",
    overall: 135,
    safety_and_security: 143,
    personal_freedom: 65,
    governance: 94,
    social_capital: 120,
    investment_environment: 134,
    enterprise_conditions: 126,
    infrastructure_and_market_access: 152,
    economic_quality: 125,
    living_conditions: 152,
    health: 132,
    education: 161,
    natural_environment: 85,
  },
  {
    country: "Pakistan",
    overall: 136,
    safety_and_security: 149,
    personal_freedom: 120,
    governance: 118,
    social_capital: 123,
    investment_environment: 96,
    enterprise_conditions: 102,
    infrastructure_and_market_access: 124,
    economic_quality: 129,
    living_conditions: 119,
    health: 124,
    education: 140,
    natural_environment: 166,
  },
  {
    country: "Madagascar",
    overall: 137,
    safety_and_security: 121,
    personal_freedom: 81,
    governance: 120,
    social_capital: 111,
    investment_environment: 136,
    enterprise_conditions: 127,
    infrastructure_and_market_access: 140,
    economic_quality: 143,
    living_conditions: 164,
    health: 145,
    education: 146,
    natural_environment: 79,
  },
  {
    country: "Liberia",
    overall: 138,
    safety_and_security: 112,
    personal_freedom: 89,
    governance: 109,
    social_capital: 98,
    investment_environment: 146,
    enterprise_conditions: 106,
    infrastructure_and_market_access: 163,
    economic_quality: 149,
    living_conditions: 145,
    health: 160,
    education: 159,
    natural_environment: 61,
  },
  {
    country: "Zimbabwe",
    overall: 139,
    safety_and_security: 110,
    personal_freedom: 134,
    governance: 147,
    social_capital: 135,
    investment_environment: 156,
    enterprise_conditions: 147,
    infrastructure_and_market_access: 132,
    economic_quality: 145,
    living_conditions: 139,
    health: 141,
    education: 98,
    natural_environment: 110,
  },
  {
    country: "Iraq",
    overall: 140,
    safety_and_security: 163,
    personal_freedom: 133,
    governance: 135,
    social_capital: 138,
    investment_environment: 127,
    enterprise_conditions: 144,
    infrastructure_and_market_access: 107,
    economic_quality: 105,
    living_conditions: 87,
    health: 115,
    education: 121,
    natural_environment: 167,
  },
  {
    country: "Guinea",
    overall: 141,
    safety_and_security: 123,
    personal_freedom: 110,
    governance: 130,
    social_capital: 102,
    investment_environment: 128,
    enterprise_conditions: 92,
    infrastructure_and_market_access: 136,
    economic_quality: 154,
    living_conditions: 151,
    health: 159,
    education: 156,
    natural_environment: 68,
  },
  {
    country: "Nigeria",
    overall: 142,
    safety_and_security: 153,
    personal_freedom: 106,
    governance: 132,
    social_capital: 84,
    investment_environment: 123,
    enterprise_conditions: 125,
    infrastructure_and_market_access: 138,
    economic_quality: 146,
    living_conditions: 132,
    health: 157,
    education: 136,
    natural_environment: 129,
  },
  {
    country: "Myanmar",
    overall: 143,
    safety_and_security: 154,
    personal_freedom: 164,
    governance: 142,
    social_capital: 58,
    investment_environment: 159,
    enterprise_conditions: 145,
    infrastructure_and_market_access: 117,
    economic_quality: 142,
    living_conditions: 130,
    health: 109,
    education: 114,
    natural_environment: 84,
  },
  {
    country: "Sierra Leone ",
    overall: 144,
    safety_and_security: 107,
    personal_freedom: 85,
    governance: 104,
    social_capital: 86,
    investment_environment: 152,
    enterprise_conditions: 141,
    infrastructure_and_market_access: 158,
    economic_quality: 157,
    living_conditions: 156,
    health: 162,
    education: 151,
    natural_environment: 105,
  },
  {
    country: "Venezuela",
    overall: 145,
    safety_and_security: 151,
    personal_freedom: 136,
    governance: 167,
    social_capital: 60,
    investment_environment: 167,
    enterprise_conditions: 167,
    infrastructure_and_market_access: 119,
    economic_quality: 166,
    living_conditions: 96,
    health: 97,
    education: 87,
    natural_environment: 41,
  },
  {
    country: "Libya",
    overall: 146,
    safety_and_security: 162,
    personal_freedom: 129,
    governance: 160,
    social_capital: 115,
    investment_environment: 157,
    enterprise_conditions: 161,
    infrastructure_and_market_access: 128,
    economic_quality: 99,
    living_conditions: 94,
    health: 105,
    education: 112,
    natural_environment: 157,
  },
  {
    country: "Cameroon",
    overall: 147,
    safety_and_security: 155,
    personal_freedom: 127,
    governance: 148,
    social_capital: 127,
    investment_environment: 137,
    enterprise_conditions: 128,
    infrastructure_and_market_access: 134,
    economic_quality: 112,
    living_conditions: 135,
    health: 152,
    education: 115,
    natural_environment: 118,
  },
  {
    country: "Republic of the Congo",
    overall: 148,
    safety_and_security: 133,
    personal_freedom: 131,
    governance: 151,
    social_capital: 149,
    investment_environment: 138,
    enterprise_conditions: 151,
    infrastructure_and_market_access: 147,
    economic_quality: 151,
    living_conditions: 133,
    health: 146,
    education: 116,
    natural_environment: 94,
  },
  {
    country: "Guinea-Bissau",
    overall: 149,
    safety_and_security: 54,
    personal_freedom: 99,
    governance: 138,
    social_capital: 121,
    investment_environment: 158,
    enterprise_conditions: 142,
    infrastructure_and_market_access: 155,
    economic_quality: 153,
    living_conditions: 154,
    health: 155,
    education: 162,
    natural_environment: 69,
  },
  {
    country: "Mozambique",
    overall: 150,
    safety_and_security: 132,
    personal_freedom: 101,
    governance: 121,
    social_capital: 126,
    investment_environment: 140,
    enterprise_conditions: 143,
    infrastructure_and_market_access: 146,
    economic_quality: 158,
    living_conditions: 157,
    health: 150,
    education: 160,
    natural_environment: 50,
  },
  {
    country: "Mali",
    overall: 151,
    safety_and_security: 158,
    personal_freedom: 87,
    governance: 117,
    social_capital: 131,
    investment_environment: 148,
    enterprise_conditions: 134,
    infrastructure_and_market_access: 142,
    economic_quality: 119,
    living_conditions: 136,
    health: 144,
    education: 163,
    natural_environment: 97,
  },
  {
    country: "Niger ",
    overall: 152,
    safety_and_security: 140,
    personal_freedom: 90,
    governance: 110,
    social_capital: 76,
    investment_environment: 147,
    enterprise_conditions: 131,
    infrastructure_and_market_access: 164,
    economic_quality: 124,
    living_conditions: 160,
    health: 143,
    education: 167,
    natural_environment: 117,
  },
  {
    country: "Ethiopia",
    overall: 153,
    safety_and_security: 150,
    personal_freedom: 138,
    governance: 116,
    social_capital: 106,
    investment_environment: 155,
    enterprise_conditions: 130,
    infrastructure_and_market_access: 160,
    economic_quality: 115,
    living_conditions: 146,
    health: 122,
    education: 149,
    natural_environment: 108,
  },
  {
    country: "Mauritania",
    overall: 154,
    safety_and_security: 87,
    personal_freedom: 123,
    governance: 154,
    social_capital: 119,
    investment_environment: 161,
    enterprise_conditions: 166,
    infrastructure_and_market_access: 154,
    economic_quality: 135,
    living_conditions: 124,
    health: 138,
    education: 154,
    natural_environment: 164,
  },
  {
    country: "Angola",
    overall: 155,
    safety_and_security: 115,
    personal_freedom: 122,
    governance: 137,
    social_capital: 154,
    investment_environment: 162,
    enterprise_conditions: 163,
    infrastructure_and_market_access: 150,
    economic_quality: 120,
    living_conditions: 144,
    health: 158,
    education: 152,
    natural_environment: 124,
  },
  {
    country: "Haiti",
    overall: 156,
    safety_and_security: 127,
    personal_freedom: 104,
    governance: 158,
    social_capital: 150,
    investment_environment: 164,
    enterprise_conditions: 164,
    infrastructure_and_market_access: 151,
    economic_quality: 144,
    living_conditions: 149,
    health: 148,
    education: 143,
    natural_environment: 141,
  },
  {
    country: "Burundi",
    overall: 157,
    safety_and_security: 152,
    personal_freedom: 154,
    governance: 144,
    social_capital: 146,
    investment_environment: 151,
    enterprise_conditions: 108,
    infrastructure_and_market_access: 157,
    economic_quality: 163,
    living_conditions: 165,
    health: 134,
    education: 150,
    natural_environment: 101,
  },
  {
    country: "Sudan",
    overall: 158,
    safety_and_security: 159,
    personal_freedom: 153,
    governance: 145,
    social_capital: 164,
    investment_environment: 149,
    enterprise_conditions: 155,
    infrastructure_and_market_access: 139,
    economic_quality: 167,
    living_conditions: 138,
    health: 127,
    education: 144,
    natural_environment: 163,
  },
  {
    country: "Syria",
    overall: 159,
    safety_and_security: 164,
    personal_freedom: 167,
    governance: 165,
    social_capital: 167,
    investment_environment: 143,
    enterprise_conditions: 165,
    infrastructure_and_market_access: 149,
    economic_quality: 148,
    living_conditions: 106,
    health: 108,
    education: 128,
    natural_environment: 160,
  },
  {
    country: "Eritrea",
    overall: 160,
    safety_and_security: 137,
    personal_freedom: 166,
    governance: 163,
    social_capital: 158,
    investment_environment: 144,
    enterprise_conditions: 152,
    infrastructure_and_market_access: 161,
    economic_quality: 156,
    living_conditions: 162,
    health: 135,
    education: 153,
    natural_environment: 130,
  },
  {
    country: "DR Congo",
    overall: 161,
    safety_and_security: 161,
    personal_freedom: 117,
    governance: 159,
    social_capital: 151,
    investment_environment: 166,
    enterprise_conditions: 158,
    infrastructure_and_market_access: 162,
    economic_quality: 159,
    living_conditions: 163,
    health: 154,
    education: 147,
    natural_environment: 102,
  },
  {
    country: "Chad",
    overall: 162,
    safety_and_security: 145,
    personal_freedom: 132,
    governance: 162,
    social_capital: 147,
    investment_environment: 163,
    enterprise_conditions: 157,
    infrastructure_and_market_access: 167,
    economic_quality: 141,
    living_conditions: 161,
    health: 165,
    education: 166,
    natural_environment: 103,
  },
  {
    country: "Somalia",
    overall: 163,
    safety_and_security: 160,
    personal_freedom: 141,
    governance: 161,
    social_capital: 143,
    investment_environment: 153,
    enterprise_conditions: 140,
    infrastructure_and_market_access: 165,
    economic_quality: 165,
    living_conditions: 159,
    health: 163,
    education: 158,
    natural_environment: 136,
  },
  {
    country: "Afghanistan",
    overall: 164,
    safety_and_security: 166,
    personal_freedom: 148,
    governance: 149,
    social_capital: 166,
    investment_environment: 154,
    enterprise_conditions: 139,
    infrastructure_and_market_access: 159,
    economic_quality: 152,
    living_conditions: 153,
    health: 153,
    education: 157,
    natural_environment: 155,
  },
  {
    country: "Central African Republic",
    overall: 165,
    safety_and_security: 157,
    personal_freedom: 135,
    governance: 155,
    social_capital: 160,
    investment_environment: 160,
    enterprise_conditions: 149,
    infrastructure_and_market_access: 166,
    economic_quality: 130,
    living_conditions: 167,
    health: 167,
    education: 165,
    natural_environment: 93,
  },
  {
    country: "Yemen",
    overall: 166,
    safety_and_security: 165,
    personal_freedom: 159,
    governance: 166,
    social_capital: 157,
    investment_environment: 165,
    enterprise_conditions: 160,
    infrastructure_and_market_access: 156,
    economic_quality: 164,
    living_conditions: 148,
    health: 136,
    education: 155,
    natural_environment: 152,
  },
  {
    country: "South Sudan",
    overall: 167,
    safety_and_security: 167,
    personal_freedom: 158,
    governance: 164,
    social_capital: 163,
    investment_environment: 150,
    enterprise_conditions: 156,
    infrastructure_and_market_access: 153,
    economic_quality: 160,
    living_conditions: 166,
    health: 166,
    education: 164,
    natural_environment: 125,
  },
];
