export interface Country {
  cost_score: number;
  country: string;
  country_code: string;
  long_slug: string;
  name: string;
  name_chinese: string;
  overall_score: number;
  region: string;
  short_slug: string;
  slug: string;
}

interface CountryHash {
  [key: string]: Country;
}

export const countries: CountryHash = {
  AF: {
    cost_score: 5,
    country: "Afghanistan",
    country_code: "AF",
    long_slug: "afghanistan",
    name: "Afghanistan",
    name_chinese: "阿富汗",
    overall_score: 2.72,
    region: "Asia",
    short_slug: "afghanistan",
    slug: "afghanistan",
  },
  AL: {
    cost_score: 5,
    country: "Albania",
    country_code: "AL",
    long_slug: "albania",
    name: "Albania",
    name_chinese: "阿尔巴尼亚",
    overall_score: 3.45,
    region: "Europe",
    short_slug: "albania",
    slug: "albania",
  },
  DZ: {
    cost_score: 4.99,
    country: "Algeria",
    country_code: "DZ",
    long_slug: "algeria",
    name: "Algeria",
    name_chinese: "阿尔及利亚",
    overall_score: 3.22,
    region: "Africa",
    short_slug: "algeria",
    slug: "algeria",
  },
  AD: {
    cost_score: 3.39,
    country: "Andorra",
    country_code: "AD",
    long_slug: "andorra",
    name: "Andorra",
    name_chinese: "安道尔",
    overall_score: 3.37,
    region: "Europe",
    short_slug: "andorra",
    slug: "andorra",
  },
  AO: {
    cost_score: 4.88,
    country: "Angola",
    country_code: "AO",
    long_slug: "angola",
    name: "Angola",
    name_chinese: "安哥拉",
    overall_score: 3.4,
    region: "Africa",
    short_slug: "angola",
    slug: "angola",
  },
  AQ: {
    cost_score: 1,
    country: "Antarctica",
    country_code: "AQ",
    long_slug: "antarctica",
    name: "Antarctica",
    name_chinese: "南极洲",
    overall_score: 2.71,
    region: "Antarctica",
    short_slug: "antarctica",
    slug: "antarctica",
  },
  AG: {
    cost_score: 3.27,
    country: "Antigua and Barbuda",
    country_code: "AG",
    long_slug: "antigua-and-barbuda",
    name: "Antigua and Barbuda",
    name_chinese: "安提瓜和巴布达",
    overall_score: 3.08,
    region: "North America",
    short_slug: "antigua-and-barbuda",
    slug: "antigua-and-barbuda",
  },
  AR: {
    cost_score: 5,
    country: "Argentina",
    country_code: "AR",
    long_slug: "argentina",
    name: "Argentina",
    name_chinese: "阿根廷",
    overall_score: 3.38,
    region: "Latin America",
    short_slug: "argentina",
    slug: "argentina",
  },
  AM: {
    cost_score: 5,
    country: "Armenia",
    country_code: "AM",
    long_slug: "armenia",
    name: "Armenia",
    name_chinese: "亚美尼亚",
    overall_score: 3.57,
    region: "Europe",
    short_slug: "armenia",
    slug: "armenia",
  },
  AW: {
    cost_score: 2.51,
    country: "Aruba",
    country_code: "AW",
    long_slug: "aruba",
    name: "Aruba",
    name_chinese: "阿鲁巴",
    overall_score: 3.3,
    region: "North America",
    short_slug: "aruba",
    slug: "aruba",
  },
  AU: {
    cost_score: 3.04,
    country: "Australia",
    country_code: "AU",
    long_slug: "australia",
    name: "Australia",
    name_chinese: "澳大利亚",
    overall_score: 3.49,
    region: "Oceania",
    short_slug: "australia",
    slug: "australia",
  },
  AT: {
    cost_score: 3.46,
    country: "Austria",
    country_code: "AT",
    long_slug: "austria",
    name: "Austria",
    name_chinese: "奥地利",
    overall_score: 3.28,
    region: "Europe",
    short_slug: "austria",
    slug: "austria",
  },
  AZ: {
    cost_score: 5,
    country: "Azerbaijan",
    country_code: "AZ",
    long_slug: "azerbaijan",
    name: "Azerbaijan",
    name_chinese: "阿塞拜疆",
    overall_score: 3.13,
    region: "Europe",
    short_slug: "azerbaijan",
    slug: "azerbaijan",
  },
  BS: {
    cost_score: 1.53,
    country: "The Bahamas",
    country_code: "BS",
    long_slug: "bahamas",
    name: "The Bahamas",
    name_chinese: "巴哈马群岛",
    overall_score: 2.81,
    region: "North America",
    short_slug: "bahamas",
    slug: "bahamas",
  },
  BH: {
    cost_score: 4.45,
    country: "Bahrain",
    country_code: "BH",
    long_slug: "bahrain",
    name: "Bahrain",
    name_chinese: "巴林",
    overall_score: 3.3,
    region: "Asia",
    short_slug: "bahrain",
    slug: "bahrain",
  },
  BD: {
    cost_score: 4.89,
    country: "Bangladesh",
    country_code: "BD",
    long_slug: "bangladesh",
    name: "Bangladesh",
    name_chinese: "孟加拉国",
    overall_score: 3.31,
    region: "Asia",
    short_slug: "bangladesh",
    slug: "bangladesh",
  },
  BB: {
    cost_score: 2.37,
    country: "Barbados",
    country_code: "BB",
    long_slug: "barbados",
    name: "Barbados",
    name_chinese: "巴巴多斯",
    overall_score: 2.71,
    region: "North America",
    short_slug: "barbados",
    slug: "barbados",
  },
  BY: {
    cost_score: 5,
    country: "Belarus",
    country_code: "BY",
    long_slug: "belarus",
    name: "Belarus",
    name_chinese: "白俄罗斯",
    overall_score: 3.48,
    region: "Europe",
    short_slug: "belarus",
    slug: "belarus",
  },
  BE: {
    cost_score: 2.77,
    country: "Belgium",
    country_code: "BE",
    long_slug: "belgium",
    name: "Belgium",
    name_chinese: "比利时",
    overall_score: 3.13,
    region: "Europe",
    short_slug: "belgium",
    slug: "belgium",
  },
  BZ: {
    cost_score: 4.12,
    country: "Belize",
    country_code: "BZ",
    long_slug: "belize",
    name: "Belize",
    name_chinese: "伯利兹",
    overall_score: 2.99,
    region: "North America",
    short_slug: "belize",
    slug: "belize",
  },
  BJ: {
    cost_score: 4.02,
    country: "Benin",
    country_code: "BJ",
    long_slug: "benin",
    name: "Benin",
    name_chinese: "贝宁",
    overall_score: 2.33,
    region: "Africa",
    short_slug: "benin",
    slug: "benin",
  },
  BM: {
    cost_score: 1,
    country: "Bermuda",
    country_code: "BM",
    long_slug: "bermuda",
    name: "Bermuda",
    name_chinese: "百慕大",
    overall_score: 2.7,
    region: "North America",
    short_slug: "bermuda",
    slug: "bermuda",
  },
  BT: {
    cost_score: 3.12,
    country: "Bhutan",
    country_code: "BT",
    long_slug: "bhutan",
    name: "Bhutan",
    name_chinese: "不丹",
    overall_score: 3.93,
    region: "Asia",
    short_slug: "bhutan",
    slug: "bhutan",
  },
  BO: {
    cost_score: 4.92,
    country: "Bolivia",
    country_code: "BO",
    long_slug: "bolivia",
    name: "Bolivia",
    name_chinese: "玻利维亚",
    overall_score: 2.92,
    region: "Latin America",
    short_slug: "bolivia",
    slug: "bolivia",
  },
  BQ: {
    cost_score: 1.48,
    country: "Bonaire",
    country_code: "BQ",
    long_slug: "bonaire",
    name: "Bonaire",
    name_chinese: "博内尔",
    overall_score: 2.55,
    region: "Latin America",
    short_slug: "bonaire",
    slug: "bonaire",
  },
  BA: {
    cost_score: 5,
    country: "Bosnia and Herzegovina",
    country_code: "BA",
    long_slug: "bosnia",
    name: "Bosnia",
    name_chinese: "波斯尼亚",
    overall_score: 3.55,
    region: "Europe",
    short_slug: "bosnia",
    slug: "bosnia",
  },
  BW: {
    cost_score: 5,
    country: "Botswana",
    country_code: "BW",
    long_slug: "botswana",
    name: "Botswana",
    name_chinese: "博茨瓦纳",
    overall_score: 3.46,
    region: "Africa",
    short_slug: "botswana",
    slug: "botswana",
  },
  BR: {
    cost_score: 5,
    country: "Brazil",
    country_code: "BR",
    long_slug: "brazil",
    name: "Brazil",
    name_chinese: "巴西",
    overall_score: 3.27,
    region: "Latin America",
    short_slug: "brazil",
    slug: "brazil",
  },
  BN: {
    cost_score: 5,
    country: "Brunei",
    country_code: "BN",
    long_slug: "brunei",
    name: "Brunei",
    name_chinese: "文莱",
    overall_score: 3.39,
    region: "Asia",
    short_slug: "brunei",
    slug: "brunei",
  },
  BG: {
    cost_score: 5,
    country: "Bulgaria",
    country_code: "BG",
    long_slug: "bulgaria",
    name: "Bulgaria",
    name_chinese: "保加利亚",
    overall_score: 3.82,
    region: "Europe",
    short_slug: "bulgaria",
    slug: "bulgaria",
  },
  BI: {
    cost_score: 3.02,
    country: "Burundi",
    country_code: "BI",
    long_slug: "burundi",
    name: "Burundi",
    name_chinese: "布隆迪",
    overall_score: 3.33,
    region: "Africa",
    short_slug: "burundi",
    slug: "burundi",
  },
  BF: {
    cost_score: 4.71,
    country: "Burkina Faso",
    country_code: "BF",
    long_slug: "burkina-faso",
    name: "Burkina Faso",
    name_chinese: "布基纳法索",
    overall_score: 3.09,
    region: "Africa",
    short_slug: "burkina-faso",
    slug: "burkina-faso",
  },
  CV: {
    cost_score: 4.13,
    country: "Cabo Verde",
    country_code: "CV",
    long_slug: "cape-verde",
    name: "Cabo Verde",
    name_chinese: "佛得角",
    overall_score: 3.14,
    region: "Africa",
    short_slug: "cape-verde",
    slug: "cape-verde",
  },
  KH: {
    cost_score: 5,
    country: "Cambodia",
    country_code: "KH",
    long_slug: "cambodia",
    name: "Cambodia",
    name_chinese: "柬埔寨",
    overall_score: 3.73,
    region: "Asia",
    short_slug: "cambodia",
    slug: "cambodia",
  },
  CM: {
    cost_score: 5,
    country: "Cameroon",
    country_code: "CM",
    long_slug: "cameroon",
    name: "Cameroon",
    name_chinese: "喀麦隆",
    overall_score: 3.29,
    region: "Africa",
    short_slug: "cameroon",
    slug: "cameroon",
  },
  CA: {
    cost_score: 3.56,
    country: "Canada",
    country_code: "CA",
    long_slug: "canada",
    name: "Canada",
    name_chinese: "加拿大",
    overall_score: 3.49,
    region: "North America",
    short_slug: "canada",
    slug: "canada",
  },
  KY: {
    cost_score: 1,
    country: "Cayman Islands",
    country_code: "KY",
    long_slug: "cayman-islands",
    name: "Cayman Islands",
    name_chinese: "开曼群岛",
    overall_score: 2.77,
    region: "North America",
    short_slug: "cayman-islands",
    slug: "cayman-islands",
  },
  CF: {
    cost_score: 4.16,
    country: "Central African Republic",
    country_code: "CF",
    long_slug: "central-african-republic",
    name: "Central African Republic",
    name_chinese: "中非共和国",
    overall_score: 2.71,
    region: "Africa",
    short_slug: "central-african-republic",
    slug: "central-african-republic",
  },
  TD: {
    cost_score: 1.11,
    country: "Chad",
    country_code: "TD",
    long_slug: "chad",
    name: "Chad",
    name_chinese: "乍得",
    overall_score: 1.76,
    region: "Africa",
    short_slug: "chad",
    slug: "chad",
  },
  CL: {
    cost_score: 4.69,
    country: "Chile",
    country_code: "CL",
    long_slug: "chile",
    name: "Chile",
    name_chinese: "智利",
    overall_score: 3.24,
    region: "Latin America",
    short_slug: "chile",
    slug: "chile",
  },
  CN: {
    cost_score: 5,
    country: "China",
    country_code: "CN",
    long_slug: "china",
    name: "China",
    name_chinese: "中国",
    overall_score: 2.98,
    region: "Asia",
    short_slug: "china",
    slug: "china",
  },
  CO: {
    cost_score: 5,
    country: "Colombia",
    country_code: "CO",
    long_slug: "colombia",
    name: "Colombia",
    name_chinese: "哥伦比亚",
    overall_score: 3.23,
    region: "Latin America",
    short_slug: "colombia",
    slug: "colombia",
  },
  KM: {
    cost_score: 3.02,
    country: "Comoros",
    country_code: "KM",
    long_slug: "comoros",
    name: "Comoros",
    name_chinese: "科摩罗",
    overall_score: 3.33,
    region: "Africa",
    short_slug: "comoros",
    slug: "comoros",
  },
  CK: {
    cost_score: 2.31,
    country: "Cook Islands",
    country_code: "CK",
    long_slug: "cook-islands",
    name: "Cook Islands",
    name_chinese: "库克群岛",
    overall_score: 2.79,
    region: "Oceania",
    short_slug: "cook-islands",
    slug: "cook-islands",
  },
  CG: {
    cost_score: 4.67,
    country: "Congo",
    country_code: "CG",
    long_slug: "congo",
    name: "Congo",
    name_chinese: "刚果",
    overall_score: 3.26,
    region: "Africa",
    short_slug: "congo",
    slug: "congo",
  },
  CD: {
    cost_score: 5,
    country: "DR Congo",
    country_code: "CD",
    long_slug: "dr-congo",
    name: "DR Congo",
    name_chinese: "刚果民主共和国",
    overall_score: 3.19,
    region: "Africa",
    short_slug: "dr-congo",
    slug: "dr-congo",
  },
  CR: {
    cost_score: 4.17,
    country: "Costa Rica",
    country_code: "CR",
    long_slug: "costa-rica",
    name: "Costa Rica",
    name_chinese: "哥斯达黎加",
    overall_score: 3.31,
    region: "North America",
    short_slug: "costa-rica",
    slug: "costa-rica",
  },
  HR: {
    cost_score: 4.52,
    country: "Croatia",
    country_code: "HR",
    long_slug: "croatia",
    name: "Croatia",
    name_chinese: "克罗地亚",
    overall_score: 3.52,
    region: "Europe",
    short_slug: "croatia",
    slug: "croatia",
  },
  CU: {
    cost_score: 5,
    country: "Cuba",
    country_code: "CU",
    long_slug: "cuba",
    name: "Cuba",
    name_chinese: "古巴",
    overall_score: 3.69,
    region: "North America",
    short_slug: "cuba",
    slug: "cuba",
  },
  CW: {
    cost_score: 4.66,
    country: "Curaçao",
    country_code: "CW",
    long_slug: "curacao",
    name: "Curaçao",
    name_chinese: "库拉索",
    overall_score: 3.93,
    region: "North America",
    short_slug: "curacao",
    slug: "curacao",
  },
  CY: {
    cost_score: 3.09,
    country: "Cyprus",
    country_code: "CY",
    long_slug: "cyprus",
    name: "Cyprus",
    name_chinese: "塞浦路斯",
    overall_score: 3.15,
    region: "Europe",
    short_slug: "cyprus",
    slug: "cyprus",
  },
  CZ: {
    cost_score: 4.63,
    country: "Czechia",
    country_code: "CZ",
    long_slug: "czechia",
    name: "Czechia",
    name_chinese: "捷克的",
    overall_score: 4.24,
    region: "Europe",
    short_slug: "czechia",
    slug: "czechia",
  },
  DK: {
    cost_score: 1.76,
    country: "Denmark",
    country_code: "DK",
    long_slug: "denmark",
    name: "Denmark",
    name_chinese: "丹麦",
    overall_score: 3.1,
    region: "Europe",
    short_slug: "denmark",
    slug: "denmark",
  },
  DJ: {
    cost_score: 3.1,
    country: "Djibouti",
    country_code: "DJ",
    long_slug: "djibouti",
    name: "Djibouti",
    name_chinese: "吉布提",
    overall_score: 2.31,
    region: "Africa",
    short_slug: "djibouti",
    slug: "djibouti",
  },
  DM: {
    cost_score: 0,
    country: "Dominica",
    country_code: "DM",
    long_slug: "dominica",
    name: "Dominica",
    name_chinese: "多米尼克",
    overall_score: 0,
    region: "North America",
    short_slug: "dominica",
    slug: "dominica",
  },
  DO: {
    cost_score: 4.52,
    country: "Dominican Republic",
    country_code: "DO",
    long_slug: "dominican-republic",
    name: "Dominican Republic",
    name_chinese: "多明尼加共和国",
    overall_score: 3.16,
    region: "North America",
    short_slug: "dominican-republic",
    slug: "dominican-republic",
  },
  EC: {
    cost_score: 5,
    country: "Ecuador",
    country_code: "EC",
    long_slug: "ecuador",
    name: "Ecuador",
    name_chinese: "厄瓜多尔",
    overall_score: 3.34,
    region: "Latin America",
    short_slug: "ecuador",
    slug: "ecuador",
  },
  EG: {
    cost_score: 5,
    country: "Egypt",
    country_code: "EG",
    long_slug: "egypt",
    name: "Egypt",
    name_chinese: "埃及",
    overall_score: 3.39,
    region: "Africa",
    short_slug: "egypt",
    slug: "egypt",
  },
  SV: {
    cost_score: 5,
    country: "El Salvador",
    country_code: "SV",
    long_slug: "el-salvador",
    name: "El Salvador",
    name_chinese: "萨尔瓦多",
    overall_score: 3.04,
    region: "North America",
    short_slug: "el-salvador",
    slug: "el-salvador",
  },
  GW: {
    cost_score: 4.02,
    country: "Guinea-Bissau",
    country_code: "GW",
    long_slug: "guinea-bissau",
    name: "Guinea-Bissau",
    name_chinese: "几内亚比绍",
    overall_score: 2.33,
    region: "Africa",
    short_slug: "guinea-bissau",
    slug: "guinea-bissau",
  },
  GQ: {
    cost_score: 5,
    country: "Equatorial Guinea",
    country_code: "GQ",
    long_slug: "equatorial_guinea",
    name: "Equatorial Guinea",
    name_chinese: "",
    overall_score: 3.15,
    region: "Africa",
    short_slug: "equatorial_guinea",
    slug: "equatorial_guinea",
  },
  ER: {
    cost_score: 5,
    country: "Eritrea",
    country_code: "ER",
    long_slug: "eritrea",
    name: "Eritrea",
    name_chinese: "厄立特里亚",
    overall_score: 3.08,
    region: "Africa",
    short_slug: "eritrea",
    slug: "eritrea",
  },
  SZ: {
    cost_score: 5,
    country: "Eswatini",
    country_code: "SZ",
    long_slug: "eswatini",
    name: "Eswatini",
    name_chinese: "",
    overall_score: 3.15,
    region: "Africa",
    short_slug: "eswatini",
    slug: "eswatini",
  },
  EE: {
    cost_score: 4.33,
    country: "Estonia",
    country_code: "EE",
    long_slug: "estonia",
    name: "Estonia",
    name_chinese: "爱沙尼亚",
    overall_score: 3.94,
    region: "Europe",
    short_slug: "estonia",
    slug: "estonia",
  },
  ET: {
    cost_score: 5,
    country: "Ethiopia",
    country_code: "ET",
    long_slug: "ethiopia",
    name: "Ethiopia",
    name_chinese: "埃塞俄比亚",
    overall_score: 3.15,
    region: "Africa",
    short_slug: "ethiopia",
    slug: "ethiopia",
  },
  FK: {
    cost_score: 2.12,
    country: "Falkland Islands",
    country_code: "FK",
    long_slug: "falkland-islands",
    name: "Falkland Islands",
    name_chinese: "福克兰群岛",
    overall_score: 3.04,
    region: "Latin America",
    short_slug: "falkland-islands",
    slug: "falkland-islands",
  },
  FM: {
    cost_score: 3.02,
    country: "Micronesia",
    country_code: "FM",
    long_slug: "micronesia",
    name: "Micronesia",
    name_chinese: "密克罗尼西亚",
    overall_score: 3.33,
    region: "North America",
    short_slug: "micronesia",
    slug: "micronesia",
  },
  FJ: {
    cost_score: 4.71,
    country: "Fiji",
    country_code: "FJ",
    long_slug: "fiji",
    name: "Fiji",
    name_chinese: "斐",
    overall_score: 3.8,
    region: "Oceania",
    short_slug: "fiji",
    slug: "fiji",
  },
  FI: {
    cost_score: 3.13,
    country: "Finland",
    country_code: "FI",
    long_slug: "finland",
    name: "Finland",
    name_chinese: "芬兰",
    overall_score: 3.32,
    region: "Europe",
    short_slug: "finland",
    slug: "finland",
  },
  FR: {
    cost_score: 2.78,
    country: "France",
    country_code: "FR",
    long_slug: "france",
    name: "France",
    name_chinese: "法国",
    overall_score: 3.02,
    region: "Europe",
    short_slug: "france",
    slug: "france",
  },
  GF: {
    cost_score: 2.87,
    country: "French Guiana",
    country_code: "GF",
    long_slug: "french-guiana",
    name: "French Guiana",
    name_chinese: "法属圭亚那",
    overall_score: 2.48,
    region: "Latin America",
    short_slug: "french-guiana",
    slug: "french-guiana",
  },
  GA: {
    cost_score: 3.03,
    country: "Gabon",
    country_code: "GA",
    long_slug: "gabon",
    name: "Gabon",
    name_chinese: "加蓬",
    overall_score: 2.67,
    region: "Africa",
    short_slug: "gabon",
    slug: "gabon",
  },
  GM: {
    cost_score: 5,
    country: "Gambia",
    country_code: "GM",
    long_slug: "gambia",
    name: "Gambia",
    name_chinese: "冈比亚",
    overall_score: 3.17,
    region: "Africa",
    short_slug: "gambia",
    slug: "gambia",
  },
  GE: {
    cost_score: 5,
    country: "Georgia",
    country_code: "GE",
    long_slug: "georgia",
    name: "Georgia",
    name_chinese: "格鲁吉亚",
    overall_score: 3.38,
    region: "Europe",
    short_slug: "georgia",
    slug: "georgia",
  },
  DE: {
    cost_score: 3.46,
    country: "Germany",
    country_code: "DE",
    long_slug: "germany",
    name: "Germany",
    name_chinese: "德国",
    overall_score: 3.29,
    region: "Europe",
    short_slug: "germany",
    slug: "germany",
  },
  GH: {
    cost_score: 3.93,
    country: "Ghana",
    country_code: "GH",
    long_slug: "ghana",
    name: "Ghana",
    name_chinese: "加纳",
    overall_score: 2.98,
    region: "Africa",
    short_slug: "ghana",
    slug: "ghana",
  },
  GI: {
    cost_score: 2.11,
    country: "Gibraltar",
    country_code: "GI",
    long_slug: "gibraltar",
    name: "Gibraltar",
    name_chinese: "直布罗陀",
    overall_score: 3.14,
    region: "Europe",
    short_slug: "gibraltar",
    slug: "gibraltar",
  },
  GR: {
    cost_score: 3.13,
    country: "Greece",
    country_code: "GR",
    long_slug: "greece",
    name: "Greece",
    name_chinese: "希腊",
    overall_score: 3.04,
    region: "Europe",
    short_slug: "greece",
    slug: "greece",
  },
  GL: {
    cost_score: 3.84,
    country: "Greenland",
    country_code: "GL",
    long_slug: "greenland",
    name: "Greenland",
    name_chinese: "格陵兰",
    overall_score: 3.19,
    region: "North America",
    short_slug: "greenland",
    slug: "greenland",
  },
  GD: {
    cost_score: 0,
    country: "Grenada",
    country_code: "GD",
    long_slug: "grenada",
    name: "Grenada",
    name_chinese: "格林纳达",
    overall_score: 3.5,
    region: "North America",
    short_slug: "grenada",
    slug: "grenada",
  },
  GU: {
    cost_score: 2.67,
    country: "Guam",
    country_code: "GU",
    long_slug: "guam",
    name: "Guam",
    name_chinese: "关岛",
    overall_score: 3.16,
    region: "Oceania",
    short_slug: "guam",
    slug: "guam",
  },
  GP: {
    cost_score: 3.95,
    country: "Guadeloupe",
    country_code: "GP",
    long_slug: "guadeloupe",
    name: "Guadeloupe",
    name_chinese: "瓜德罗普岛",
    overall_score: 2.81,
    region: "North America",
    short_slug: "guadeloupe",
    slug: "guadeloupe",
  },
  GT: {
    cost_score: 5,
    country: "Guatemala",
    country_code: "GT",
    long_slug: "guatemala",
    name: "Guatemala",
    name_chinese: "危地马拉",
    overall_score: 3.01,
    region: "North America",
    short_slug: "guatemala",
    slug: "guatemala",
  },
  GG: {
    cost_score: 5,
    country: "Guernsey, Channel Island",
    country_code: "GG",
    long_slug: "guernsey",
    name: "Guernsey, Channel Island",
    name_chinese: "",
    overall_score: 3.55,
    region: "Europe",
    short_slug: "guernsey",
    slug: "guernsey",
  },
  GN: {
    cost_score: 5,
    country: "Guinea",
    country_code: "GN",
    long_slug: "guinea",
    name: "Guinea",
    name_chinese: "几内亚",
    overall_score: 3.18,
    region: "Africa",
    short_slug: "guinea",
    slug: "guinea",
  },
  GY: {
    cost_score: 5,
    country: "Guyana",
    country_code: "GY",
    long_slug: "guyana",
    name: "Guyana",
    name_chinese: "圭亚那",
    overall_score: 3.55,
    region: "Latin America",
    short_slug: "guyana",
    slug: "guyana",
  },
  HT: {
    cost_score: 3.32,
    country: "Haiti",
    country_code: "HT",
    long_slug: "haiti",
    name: "Haiti",
    name_chinese: "海地",
    overall_score: 2.72,
    region: "North America",
    short_slug: "haiti",
    slug: "haiti",
  },
  HN: {
    cost_score: 4.77,
    country: "Honduras",
    country_code: "HN",
    long_slug: "honduras",
    name: "Honduras",
    name_chinese: "洪都拉斯",
    overall_score: 2.96,
    region: "North America",
    short_slug: "honduras",
    slug: "honduras",
  },
  HK: {
    cost_score: 3.93,
    country: "Hong Kong",
    country_code: "HK",
    long_slug: "hong-kong",
    name: "Hong Kong",
    name_chinese: "香港",
    overall_score: 3.25,
    region: "Asia",
    short_slug: "hong-kong",
    slug: "hong-kong",
  },
  HU: {
    cost_score: 4.89,
    country: "Hungary",
    country_code: "HU",
    long_slug: "hungary",
    name: "Hungary",
    name_chinese: "匈牙利",
    overall_score: 3.87,
    region: "Europe",
    short_slug: "hungary",
    slug: "hungary",
  },
  IS: {
    cost_score: 2.81,
    country: "Iceland",
    country_code: "IS",
    long_slug: "iceland",
    name: "Iceland",
    name_chinese: "冰岛",
    overall_score: 3.64,
    region: "Europe",
    short_slug: "iceland",
    slug: "iceland",
  },
  IN: {
    cost_score: 5,
    country: "India",
    country_code: "IN",
    long_slug: "india",
    name: "India",
    name_chinese: "印度",
    overall_score: 3.19,
    region: "Asia",
    short_slug: "india",
    slug: "india",
  },
  ID: {
    cost_score: 5,
    country: "Indonesia",
    country_code: "ID",
    long_slug: "indonesia",
    name: "Indonesia",
    name_chinese: "印度尼西亚",
    overall_score: 3.53,
    region: "Asia",
    short_slug: "indonesia",
    slug: "indonesia",
  },
  IR: {
    cost_score: 5,
    country: "Iran",
    country_code: "IR",
    long_slug: "iran",
    name: "Iran",
    name_chinese: "伊朗",
    overall_score: 2.98,
    region: "Asia",
    short_slug: "iran",
    slug: "iran",
  },
  IQ: {
    cost_score: 4.81,
    country: "Iraq",
    country_code: "IQ",
    long_slug: "iraq",
    name: "Iraq",
    name_chinese: "伊拉克",
    overall_score: 2.8,
    region: "Asia",
    short_slug: "iraq",
    slug: "iraq",
  },
  IE: {
    cost_score: 2.42,
    country: "Ireland",
    country_code: "IE",
    long_slug: "ireland",
    name: "Ireland",
    name_chinese: "爱尔兰",
    overall_score: 3.33,
    region: "Europe",
    short_slug: "ireland",
    slug: "ireland",
  },
  IM: {
    cost_score: 5,
    country: "Isle of Man",
    country_code: "IM",
    long_slug: "isle-of-man",
    name: "Isle of Man",
    name_chinese: "",
    overall_score: 3.55,
    region: "Europe",
    short_slug: "isle-of-man",
    slug: "isle-of-man",
  },
  IL: {
    cost_score: 1.84,
    country: "Israel",
    country_code: "IL",
    long_slug: "israel",
    name: "Israel",
    name_chinese: "以色列",
    overall_score: 2.92,
    region: "Asia",
    short_slug: "israel",
    slug: "israel",
  },
  IT: {
    cost_score: 2.68,
    country: "Italy",
    country_code: "IT",
    long_slug: "italy",
    name: "Italy",
    name_chinese: "意大利",
    overall_score: 2.96,
    region: "Europe",
    short_slug: "italy",
    slug: "italy",
  },
  CI: {
    cost_score: 3.88,
    country: "Cote d'Ivoire",
    country_code: "CI",
    long_slug: "cote-divoire",
    name: "Cote d'Ivoire",
    name_chinese: "科特迪瓦",
    overall_score: 2.93,
    region: "Africa",
    short_slug: "cote-divoire",
    slug: "cote-divoire",
  },
  JM: {
    cost_score: 4.23,
    country: "Jamaica",
    country_code: "JM",
    long_slug: "jamaica",
    name: "Jamaica",
    name_chinese: "牙买加",
    overall_score: 3.55,
    region: "North America",
    short_slug: "jamaica",
    slug: "jamaica",
  },
  JP: {
    cost_score: 3.62,
    country: "Japan",
    country_code: "JP",
    long_slug: "japan",
    name: "Japan",
    name_chinese: "日本",
    overall_score: 2.98,
    region: "Asia",
    short_slug: "japan",
    slug: "japan",
  },
  JE: {
    cost_score: 1,
    country: "Jersey, Channel Island",
    country_code: "JE",
    long_slug: "jersey",
    name: "Jersey",
    name_chinese: "",
    overall_score: 2.75,
    region: "Europe",
    short_slug: "jersey",
    slug: "jersey",
  },
  JO: {
    cost_score: 5,
    country: "Jordan",
    country_code: "JO",
    long_slug: "jordan",
    name: "Jordan",
    name_chinese: "约旦",
    overall_score: 3.61,
    region: "Asia",
    short_slug: "jordan",
    slug: "jordan",
  },
  KZ: {
    cost_score: 5,
    country: "Kazakhstan",
    country_code: "KZ",
    long_slug: "kazakhstan",
    name: "Kazakhstan",
    name_chinese: "哈萨克斯坦",
    overall_score: 3.47,
    region: "Asia",
    short_slug: "kazakhstan",
    slug: "kazakhstan",
  },
  KE: {
    cost_score: 4.61,
    country: "Kenya",
    country_code: "KE",
    long_slug: "kenya",
    name: "Kenya",
    name_chinese: "肯尼亚",
    overall_score: 3.12,
    region: "Africa",
    short_slug: "kenya",
    slug: "kenya",
  },
  KI: {
    cost_score: 3.02,
    country: "Kiribati",
    country_code: "KI",
    long_slug: "kiribati",
    name: "Kiribati",
    name_chinese: "基里巴斯",
    overall_score: 3.33,
    region: "Oceania",
    short_slug: "kiribati",
    slug: "kiribati",
  },
  KR: {
    cost_score: 4.31,
    country: "Korea, Republic of",
    country_code: "KR",
    long_slug: "south-korea",
    name: "South Korea",
    name_chinese: "韩国",
    overall_score: 3.15,
    region: "Asia",
    short_slug: "south-korea",
    slug: "south-korea",
  },
  KP: {
    cost_score: 4.61,
    country: "North Korea",
    country_code: "KP",
    long_slug: "north-korea",
    name: "North Korea",
    name_chinese: "北朝鲜",
    overall_score: 2.74,
    region: "Asia",
    short_slug: "north-korea",
    slug: "north-korea",
  },
  XK: {
    cost_score: 4.52,
    country: "Kosovo",
    country_code: "XK",
    long_slug: "kosovo",
    name: "Kosovo",
    name_chinese: "科索沃",
    overall_score: 3.08,
    region: "Europe",
    short_slug: "kosovo",
    slug: "kosovo",
  },
  KW: {
    cost_score: 3.2,
    country: "Kuwait",
    country_code: "KW",
    long_slug: "kuwait",
    name: "Kuwait",
    name_chinese: "科威特",
    overall_score: 2.73,
    region: "Asia",
    short_slug: "kuwait",
    slug: "kuwait",
  },
  KG: {
    cost_score: 5,
    country: "Kyrgyzstan",
    country_code: "KG",
    long_slug: "kyrgyzstan",
    name: "Kyrgyzstan",
    name_chinese: "吉尔吉斯斯坦",
    overall_score: 3.31,
    region: "Asia",
    short_slug: "kyrgyzstan",
    slug: "kyrgyzstan",
  },
  LA: {
    cost_score: 5,
    country: "Laos",
    country_code: "LA",
    long_slug: "laos",
    name: "Laos",
    name_chinese: "老挝",
    overall_score: 3.13,
    region: "Asia",
    short_slug: "laos",
    slug: "laos",
  },
  LV: {
    cost_score: 4.47,
    country: "Latvia",
    country_code: "LV",
    long_slug: "latvia",
    name: "Latvia",
    name_chinese: "拉脱维亚",
    overall_score: 3.49,
    region: "Europe",
    short_slug: "latvia",
    slug: "latvia",
  },
  LB: {
    cost_score: 4.75,
    country: "Lebanon",
    country_code: "LB",
    long_slug: "lebanon",
    name: "Lebanon",
    name_chinese: "黎巴嫩",
    overall_score: 3.58,
    region: "Asia",
    short_slug: "lebanon",
    slug: "lebanon",
  },
  LR: {
    cost_score: 1.43,
    country: "Liberia",
    country_code: "LR",
    long_slug: "liberia",
    name: "Liberia",
    name_chinese: "利比里亚",
    overall_score: 2.27,
    region: "Africa",
    short_slug: "liberia",
    slug: "liberia",
  },
  LY: {
    cost_score: 2.78,
    country: "Libya",
    country_code: "LY",
    long_slug: "libya",
    name: "Libya",
    name_chinese: "利比亚",
    overall_score: 2.31,
    region: "Africa",
    short_slug: "libya",
    slug: "libya",
  },
  LS: {
    cost_score: 5,
    country: "Lesotho",
    country_code: "LS",
    long_slug: "lesotho",
    name: "Lesotho",
    name_chinese: "莱索托",
    overall_score: 3.16,
    region: "Africa",
    short_slug: "lesotho",
    slug: "lesotho",
  },
  LI: {
    cost_score: 1.2,
    country: "Liechtenstein",
    country_code: "LI",
    long_slug: "liechtenstein",
    name: "Lichtenstein",
    name_chinese: "",
    overall_score: 2.31,
    region: "Europe",
    short_slug: "liechtenstein",
    slug: "liechtenstein",
  },
  LT: {
    cost_score: 4.42,
    country: "Lithuania",
    country_code: "LT",
    long_slug: "lithuania",
    name: "Lithuania",
    name_chinese: "立陶宛",
    overall_score: 3.28,
    region: "Europe",
    short_slug: "lithuania",
    slug: "lithuania",
  },
  LU: {
    cost_score: 1.2,
    country: "Luxembourg",
    country_code: "LU",
    long_slug: "luxembourg",
    name: "Luxembourg",
    name_chinese: "卢森堡",
    overall_score: 2.65,
    region: "Europe",
    short_slug: "luxembourg",
    slug: "luxembourg",
  },
  MH: {
    cost_score: 2.02,
    country: "Marshall Islands",
    country_code: "MH",
    long_slug: "marshall-islands",
    name: "Marshall Islands",
    name_chinese: "马绍尔群岛",
    overall_score: 3.33,
    region: "Oceania",
    short_slug: "marshall-islands",
    slug: "marshall-islands",
  },
  MO: {
    cost_score: 5,
    country: "Macau (SAR)",
    country_code: "MO",
    long_slug: "macau",
    name: "Macau (SAR)",
    name_chinese: "澳門",
    overall_score: 1.98,
    region: "Asia",
    short_slug: "macau",
    slug: "macau",
  },
  MG: {
    cost_score: 5,
    country: "Madagascar",
    country_code: "MG",
    long_slug: "madagascar",
    name: "Madagascar",
    name_chinese: "马达加斯加",
    overall_score: 3.18,
    region: "Africa",
    short_slug: "madagascar",
    slug: "madagascar",
  },
  MW: {
    cost_score: 4.54,
    country: "Malawi",
    country_code: "MW",
    long_slug: "malawi",
    name: "Malawi",
    name_chinese: "马拉维",
    overall_score: 3.16,
    region: "Africa",
    short_slug: "malawi",
    slug: "malawi",
  },
  MY: {
    cost_score: 5,
    country: "Malaysia",
    country_code: "MY",
    long_slug: "malaysia",
    name: "Malaysia",
    name_chinese: "马来西亚",
    overall_score: 3.44,
    region: "Asia",
    short_slug: "malaysia",
    slug: "malaysia",
  },
  MV: {
    cost_score: 5,
    country: "Maldives",
    country_code: "MV",
    long_slug: "maldives",
    name: "Maldives",
    name_chinese: "马尔代夫",
    overall_score: 3.53,
    region: "Asia",
    short_slug: "maldives",
    slug: "maldives",
  },
  ML: {
    cost_score: 3.66,
    country: "Mali",
    country_code: "ML",
    long_slug: "mali",
    name: "Mali",
    name_chinese: "马里",
    overall_score: 2.5,
    region: "Africa",
    short_slug: "mali",
    slug: "mali",
  },
  MT: {
    cost_score: 3.66,
    country: "Malta",
    country_code: "MT",
    long_slug: "malta",
    name: "Malta",
    name_chinese: "马耳他",
    overall_score: 3.64,
    region: "Europe",
    short_slug: "malta",
    slug: "malta",
  },
  MR: {
    cost_score: 4.52,
    country: "Mauritania",
    country_code: "MR",
    long_slug: "mauritania",
    name: "Mauritania",
    name_chinese: "毛里塔尼亚",
    overall_score: 2.9,
    region: "Africa",
    short_slug: "mauritania",
    slug: "mauritania",
  },
  MU: {
    cost_score: 4.42,
    country: "Mauritius",
    country_code: "MU",
    long_slug: "mauritius",
    name: "Mauritius",
    name_chinese: "毛里求斯",
    overall_score: 3.39,
    region: "Africa",
    short_slug: "mauritius",
    slug: "mauritius",
  },
  MX: {
    cost_score: 5,
    country: "Mexico",
    country_code: "MX",
    long_slug: "mexico",
    name: "Mexico",
    name_chinese: "墨西哥",
    overall_score: 3.52,
    region: "North America",
    short_slug: "mexico",
    slug: "mexico",
  },
  MD: {
    cost_score: 5,
    country: "Moldova",
    country_code: "MD",
    long_slug: "moldova",
    name: "Moldova",
    name_chinese: "摩尔多瓦",
    overall_score: 3.98,
    region: "Europe",
    short_slug: "moldova",
    slug: "moldova",
  },
  MC: {
    cost_score: 1,
    country: "Monaco",
    country_code: "MC",
    long_slug: "monaco",
    name: "Monaco",
    name_chinese: "摩纳哥",
    overall_score: 2.88,
    region: "Europe",
    short_slug: "monaco",
    slug: "monaco",
  },
  MN: {
    cost_score: 5,
    country: "Mongolia",
    country_code: "MN",
    long_slug: "mongolia",
    name: "Mongolia",
    name_chinese: "蒙古",
    overall_score: 2.71,
    region: "Asia",
    short_slug: "mongolia",
    slug: "mongolia",
  },
  ME: {
    cost_score: 4.7,
    country: "Montenegro",
    country_code: "ME",
    long_slug: "montenegro",
    name: "Montenegro",
    name_chinese: "黑山",
    overall_score: 3.3,
    region: "Europe",
    short_slug: "montenegro",
    slug: "montenegro",
  },
  MA: {
    cost_score: 4.86,
    country: "Morocco",
    country_code: "MA",
    long_slug: "morocco",
    name: "Morocco",
    name_chinese: "摩洛哥",
    overall_score: 3.52,
    region: "Africa",
    short_slug: "morocco",
    slug: "morocco",
  },
  MZ: {
    cost_score: 4.43,
    country: "Mozambique",
    country_code: "MZ",
    long_slug: "mozambique",
    name: "Mozambique",
    name_chinese: "莫桑比克",
    overall_score: 2.83,
    region: "Africa",
    short_slug: "mozambique",
    slug: "mozambique",
  },
  MM: {
    cost_score: 4.34,
    country: "Myanmar",
    country_code: "MM",
    long_slug: "myanmar",
    name: "Myanmar",
    name_chinese: "缅甸",
    overall_score: 3.11,
    region: "Asia",
    short_slug: "myanmar",
    slug: "myanmar",
  },
  NA: {
    cost_score: 4.78,
    country: "Namibia",
    country_code: "NA",
    long_slug: "namibia",
    name: "Namibia",
    name_chinese: "纳米比亚",
    overall_score: 3.38,
    region: "Africa",
    short_slug: "namibia",
    slug: "namibia",
  },
  NR: {
    cost_score: 3.02,
    country: "Nauru",
    country_code: "NR",
    long_slug: "nauru",
    name: "Nauru",
    name_chinese: "瑙鲁",
    overall_score: 3.33,
    region: "Oceania",
    short_slug: "nauru",
    slug: "nauru",
  },
  NL: {
    cost_score: 2.14,
    country: "Netherlands",
    country_code: "NL",
    long_slug: "netherlands",
    name: "Netherlands",
    name_chinese: "荷兰",
    overall_score: 3.05,
    region: "Europe",
    short_slug: "netherlands",
    slug: "netherlands",
  },
  NP: {
    cost_score: 5,
    country: "Nepal",
    country_code: "NP",
    long_slug: "nepal",
    name: "Nepal",
    name_chinese: "尼泊尔",
    overall_score: 3.76,
    region: "Asia",
    short_slug: "nepal",
    slug: "nepal",
  },
  NC: {
    cost_score: 1,
    country: "New Caledonia",
    country_code: "NC",
    long_slug: "new-caledonia",
    name: "New Caledonia",
    name_chinese: "新喀里多尼亚",
    overall_score: 2.05,
    region: "Oceania",
    short_slug: "new-caledonia",
    slug: "new-caledonia",
  },
  NZ: {
    cost_score: 3.3,
    country: "New Zealand",
    country_code: "NZ",
    long_slug: "new-zealand",
    name: "New Zealand",
    name_chinese: "新西兰",
    overall_score: 3.62,
    region: "Oceania",
    short_slug: "new-zealand",
    slug: "new-zealand",
  },
  NI: {
    cost_score: 5,
    country: "Nicaragua",
    country_code: "NI",
    long_slug: "nicaragua",
    name: "Nicaragua",
    name_chinese: "尼加拉瓜",
    overall_score: 3.26,
    region: "North America",
    short_slug: "nicaragua",
    slug: "nicaragua",
  },
  NE: {
    cost_score: 4.33,
    country: "Niger",
    country_code: "NE",
    long_slug: "niger",
    name: "Niger",
    name_chinese: "尼日尔",
    overall_score: 3.18,
    region: "Africa",
    short_slug: "niger",
    slug: "niger",
  },
  NG: {
    cost_score: 5,
    country: "Nigeria",
    country_code: "NG",
    long_slug: "nigeria",
    name: "Nigeria",
    name_chinese: "尼日利亚",
    overall_score: 3.39,
    region: "Africa",
    short_slug: "nigeria",
    slug: "nigeria",
  },
  MK: {
    cost_score: 5,
    country: "North Macedonia",
    country_code: "MK",
    long_slug: "north-macedonia",
    name: "North Macedonia",
    name_chinese: "马其顿",
    overall_score: 3.48,
    region: "Europe",
    short_slug: "north-macedonia",
    slug: "north-macedonia",
  },
  NO: {
    cost_score: 2.18,
    country: "Norway",
    country_code: "NO",
    long_slug: "norway",
    name: "Norway",
    name_chinese: "挪威",
    overall_score: 3.07,
    region: "Europe",
    short_slug: "norway",
    slug: "norway",
  },
  OM: {
    cost_score: 4.52,
    country: "Oman",
    country_code: "OM",
    long_slug: "oman",
    name: "Oman",
    name_chinese: "阿曼",
    overall_score: 3.14,
    region: "Asia",
    short_slug: "oman",
    slug: "oman",
  },
  PK: {
    cost_score: 5,
    country: "Pakistan",
    country_code: "PK",
    long_slug: "pakistan",
    name: "Pakistan",
    name_chinese: "巴基斯坦",
    overall_score: 2.76,
    region: "Asia",
    short_slug: "pakistan",
    slug: "pakistan",
  },
  PW: {
    cost_score: 3.02,
    country: "Palau",
    country_code: "PW",
    long_slug: "palau",
    name: "Palau",
    name_chinese: "帕劳",
    overall_score: 3.33,
    region: "Oceania",
    short_slug: "palau",
    slug: "palau",
  },
  PS: {
    cost_score: 4.39,
    country: "Palestinian Territories",
    country_code: "PS",
    long_slug: "palestine",
    name: "Palestinian Territories",
    name_chinese: "巴勒斯坦",
    overall_score: 3.3,
    region: "Asia",
    short_slug: "palestine",
    slug: "palestine",
  },
  PA: {
    cost_score: 3.63,
    country: "Panama",
    country_code: "PA",
    long_slug: "panama",
    name: "Panama",
    name_chinese: "巴拿马",
    overall_score: 3.18,
    region: "North America",
    short_slug: "panama",
    slug: "panama",
  },
  PG: {
    cost_score: 3.53,
    country: "Papua New Guinea",
    country_code: "PG",
    long_slug: "papua-new-guinea",
    name: "Papua New Guinea",
    name_chinese: "巴布亚新几内亚",
    overall_score: 2.78,
    region: "Oceania",
    short_slug: "papua-new-guinea",
    slug: "papua-new-guinea",
  },
  PY: {
    cost_score: 4.98,
    country: "Paraguay",
    country_code: "PY",
    long_slug: "paraguay",
    name: "Paraguay",
    name_chinese: "巴拉圭",
    overall_score: 3.4,
    region: "Latin America",
    short_slug: "paraguay",
    slug: "paraguay",
  },
  PE: {
    cost_score: 5,
    country: "Peru",
    country_code: "PE",
    long_slug: "peru",
    name: "Peru",
    name_chinese: "秘鲁",
    overall_score: 3.14,
    region: "Latin America",
    short_slug: "peru",
    slug: "peru",
  },
  PH: {
    cost_score: 5,
    country: "Philippines",
    country_code: "PH",
    long_slug: "philippines",
    name: "Philippines",
    name_chinese: "菲律宾",
    overall_score: 3.67,
    region: "Asia",
    short_slug: "philippines",
    slug: "philippines",
  },
  PL: {
    cost_score: 4.9,
    country: "Poland",
    country_code: "PL",
    long_slug: "poland",
    name: "Poland",
    name_chinese: "波兰",
    overall_score: 3.69,
    region: "Europe",
    short_slug: "poland",
    slug: "poland",
  },
  PT: {
    cost_score: 4.32,
    country: "Portugal",
    country_code: "PT",
    long_slug: "portugal",
    name: "Portugal",
    name_chinese: "葡萄牙",
    overall_score: 3.7,
    region: "Europe",
    short_slug: "portugal",
    slug: "portugal",
  },
  PR: {
    cost_score: 2.59,
    country: "Puerto Rico",
    country_code: "PR",
    long_slug: "puerto-rico",
    name: "Puerto Rico",
    name_chinese: "波多黎各",
    overall_score: 3.36,
    region: "North America",
    short_slug: "puerto-rico",
    slug: "puerto-rico",
  },
  QA: {
    cost_score: 3.46,
    country: "Qatar",
    country_code: "QA",
    long_slug: "qatar",
    name: "Qatar",
    name_chinese: "卡塔尔",
    overall_score: 2.72,
    region: "Asia",
    short_slug: "qatar",
    slug: "qatar",
  },
  RO: {
    cost_score: 5,
    country: "Romania",
    country_code: "RO",
    long_slug: "romania",
    name: "Romania",
    name_chinese: "罗马尼亚",
    overall_score: 3.88,
    region: "Europe",
    short_slug: "romania",
    slug: "romania",
  },
  RU: {
    cost_score: 5,
    country: "Russia",
    country_code: "RU",
    long_slug: "russia",
    name: "Russia",
    name_chinese: "俄国",
    overall_score: 3.16,
    region: "Europe",
    short_slug: "russia",
    slug: "russia",
  },
  RW: {
    cost_score: 5,
    country: "Rwanda",
    country_code: "RW",
    long_slug: "rwanda",
    name: "Rwanda",
    name_chinese: "卢旺达",
    overall_score: 3.29,
    region: "Africa",
    short_slug: "rwanda",
    slug: "rwanda",
  },
  SH: {
    cost_score: 1,
    country: "Saint Helena",
    country_code: "SH",
    long_slug: "saint-helena",
    name: "Saint Helena",
    name_chinese: "圣赫勒拿岛",
    overall_score: 2.77,
    region: "Africa",
    short_slug: "saint-helena",
    slug: "saint-helena",
  },
  KN: {
    cost_score: 0,
    country: "Saint Kitts and Nevis",
    country_code: "KN",
    long_slug: "saint-kitts-and-nevis",
    name: "Saint Kitts and Nevis",
    name_chinese: "聖啟斯及尼維斯",
    overall_score: 0,
    region: "Caribbean",
    short_slug: "saint-kitts",
    slug: "saint-kitts-and-nevis",
  },
  LC: {
    cost_score: 0,
    country: "Saint Lucia",
    country_code: "LC",
    long_slug: "saint-lucia",
    name: "Saint Lucia",
    name_chinese: "0",
    overall_score: 0,
    region: "Caribbean",
    short_slug: "saint-lucia",
    slug: "saint-lucia",
  },
  VC: {
    cost_score: 2.02,
    country: "Saint Vincent and the Grenadines",
    country_code: "VC",
    long_slug: "saint-vincent-and-the-grenadines",
    name: "Saint Vincent and the Grenadines",
    name_chinese: "圣文森特和格林纳丁斯",
    overall_score: 3.33,
    region: "North America",
    short_slug: "saint-vincent-and-the-grenadines",
    slug: "saint-vincent-and-the-grenadines",
  },
  WS: {
    cost_score: 4.52,
    country: "Samoa",
    country_code: "WS",
    long_slug: "samoa",
    name: "Samoa",
    name_chinese: "萨摩亚",
    overall_score: 3.58,
    region: "Oceania",
    short_slug: "samoa",
    slug: "samoa",
  },
  SM: {
    cost_score: 3.02,
    country: "San Marino",
    country_code: "SM",
    long_slug: "san-marino",
    name: "San Marino",
    name_chinese: "圣马力诺",
    overall_score: 3.33,
    region: "Europe",
    short_slug: "san-marino",
    slug: "san-marino",
  },
  ST: {
    cost_score: 3.02,
    country: "Sao Tome & Principe",
    country_code: "ST",
    long_slug: "sao-tome-and-principe",
    name: "Sao Tome & Principe",
    name_chinese: "圣多美和普林西比",
    overall_score: 3.33,
    region: "Africa",
    short_slug: "sao-tome-and-principe",
    slug: "sao-tome-and-principe",
  },
  SA: {
    cost_score: 4.37,
    country: "Saudi Arabia",
    country_code: "SA",
    long_slug: "saudi-arabia",
    name: "Saudi Arabia",
    name_chinese: "沙特阿拉伯",
    overall_score: 2.91,
    region: "Asia",
    short_slug: "saudi-arabia",
    slug: "saudi-arabia",
  },
  SN: {
    cost_score: 4.83,
    country: "Senegal",
    country_code: "SN",
    long_slug: "senegal",
    name: "Senegal",
    name_chinese: "塞内加尔",
    overall_score: 3.34,
    region: "Africa",
    short_slug: "senegal",
    slug: "senegal",
  },
  RS: {
    cost_score: 5,
    country: "Serbia",
    country_code: "RS",
    long_slug: "serbia",
    name: "Serbia",
    name_chinese: "塞尔维亚",
    overall_score: 3.6,
    region: "Europe",
    short_slug: "serbia",
    slug: "serbia",
  },
  SC: {
    cost_score: 2.94,
    country: "Seychelles",
    country_code: "SC",
    long_slug: "seychelles",
    name: "Seychelles",
    name_chinese: "塞舌尔",
    overall_score: 2.99,
    region: "Africa",
    short_slug: "seychelles",
    slug: "seychelles",
  },
  SL: {
    cost_score: 4.86,
    country: "Sierra Leone",
    country_code: "SL",
    long_slug: "sierra-leone",
    name: "Sierra Leone",
    name_chinese: "塞拉利昂",
    overall_score: 3.34,
    region: "Africa",
    short_slug: "sierra-leone",
    slug: "sierra-leone",
  },
  SG: {
    cost_score: 3.53,
    country: "Singapore",
    country_code: "SG",
    long_slug: "singapore",
    name: "Singapore",
    name_chinese: "新加坡",
    overall_score: 4.19,
    region: "Asia",
    short_slug: "singapore",
    slug: "singapore",
  },
  SX: {
    cost_score: 1.6,
    country: "Sint Maarten",
    country_code: "SX",
    long_slug: "sint-maarten",
    name: "Sint Maarten",
    name_chinese: "圣马丁岛",
    overall_score: 2.66,
    region: "North America",
    short_slug: "sint-maarten",
    slug: "sint-maarten",
  },
  SK: {
    cost_score: 4.81,
    country: "Slovak Republic",
    country_code: "SK",
    long_slug: "slovakia",
    name: "Slovak Republic",
    name_chinese: "斯洛伐克",
    overall_score: 3.56,
    region: "Europe",
    short_slug: "slovakia",
    slug: "slovakia",
  },
  SI: {
    cost_score: 4.33,
    country: "Slovenia",
    country_code: "SI",
    long_slug: "slovenia",
    name: "Slovenia",
    name_chinese: "斯洛文尼亚",
    overall_score: 3.85,
    region: "Europe",
    short_slug: "slovenia",
    slug: "slovenia",
  },
  SB: {
    cost_score: 2.99,
    country: "Solomon Islands",
    country_code: "SB",
    long_slug: "solomon-islands",
    name: "Solomon Islands",
    name_chinese: "所罗门群岛",
    overall_score: 2.89,
    region: "Oceania",
    short_slug: "solomon-islands",
    slug: "solomon-islands",
  },
  SO: {
    cost_score: 3.57,
    country: "Somalia",
    country_code: "SO",
    long_slug: "somalia",
    name: "Somalia",
    name_chinese: "索马里",
    overall_score: 2.38,
    region: "Africa",
    short_slug: "somalia",
    slug: "somalia",
  },
  ZA: {
    cost_score: 4.75,
    country: "South Africa",
    country_code: "ZA",
    long_slug: "south-africa",
    name: "South Africa",
    name_chinese: "南非",
    overall_score: 3.7,
    region: "Africa",
    short_slug: "south-africa",
    slug: "south-africa",
  },
  GS: {
    cost_score: 2.99,
    country: "South Georgia and the South Sandwich Islands",
    country_code: "GS",
    long_slug: "south-georgia-and-the-south-sandwich-islands",
    name: "South Georgia and the South Sandwich Islands",
    name_chinese: "南乔治亚岛和南桑威奇群岛",
    overall_score: 3.09,
    region: "Latin America",
    short_slug: "south-georgia-and-the-south-sandwich-islands",
    slug: "south-georgia-and-the-south-sandwich-islands",
  },
  SS: {
    cost_score: 5,
    country: "South Sudan",
    country_code: "SS",
    long_slug: "south-sudan",
    name: "South Sudan",
    name_chinese: "南苏丹",
    overall_score: 3.03,
    region: "Africa",
    short_slug: "south-sudan",
    slug: "south-sudan",
  },
  ES: {
    cost_score: 3.71,
    country: "Spain",
    country_code: "ES",
    long_slug: "spain",
    name: "Spain",
    name_chinese: "西班牙",
    overall_score: 3.36,
    region: "Europe",
    short_slug: "spain",
    slug: "spain",
  },
  LK: {
    cost_score: 5,
    country: "Sri Lanka",
    country_code: "LK",
    long_slug: "sri-lanka",
    name: "Sri Lanka",
    name_chinese: "斯里兰卡",
    overall_score: 3.64,
    region: "Asia",
    short_slug: "sri-lanka",
    slug: "sri-lanka",
  },
  SD: {
    cost_score: 5,
    country: "Sudan",
    country_code: "SD",
    long_slug: "sudan",
    name: "Sudan",
    name_chinese: "苏丹",
    overall_score: 3.26,
    region: "Africa",
    short_slug: "sudan",
    slug: "sudan",
  },
  SR: {
    cost_score: 5,
    country: "Suriname",
    country_code: "SR",
    long_slug: "suriname",
    name: "Suriname",
    name_chinese: "苏里南",
    overall_score: 3.61,
    region: "Latin America",
    short_slug: "suriname",
    slug: "suriname",
  },
  SE: {
    cost_score: 3.17,
    country: "Sweden",
    country_code: "SE",
    long_slug: "sweden",
    name: "Sweden",
    name_chinese: "瑞典",
    overall_score: 3.54,
    region: "Europe",
    short_slug: "sweden",
    slug: "sweden",
  },
  CH: {
    cost_score: 1,
    country: "Switzerland",
    country_code: "CH",
    long_slug: "switzerland",
    name: "Switzerland",
    name_chinese: "瑞士",
    overall_score: 2.74,
    region: "Europe",
    short_slug: "switzerland",
    slug: "switzerland",
  },
  SY: {
    cost_score: 4.91,
    country: "Syria",
    country_code: "SY",
    long_slug: "syria",
    name: "Syria",
    name_chinese: "叙利亚",
    overall_score: 2.76,
    region: "Asia",
    short_slug: "syria",
    slug: "syria",
  },
  TW: {
    cost_score: 3.87,
    country: "China (Taiwan)",
    country_code: "TW",
    long_slug: "taiwan",
    name: "Taiwan",
    name_chinese: "瑞典",
    overall_score: 4.34,
    region: "Asia",
    short_slug: "taiwan",
    slug: "taiwan",
  },
  TJ: {
    cost_score: 5,
    country: "Tajikistan",
    country_code: "TJ",
    long_slug: "tajikistan",
    name: "Tajikistan",
    name_chinese: "塔吉克斯坦",
    overall_score: 2.93,
    region: "Asia",
    short_slug: "tajikistan",
    slug: "tajikistan",
  },
  TZ: {
    cost_score: 5,
    country: "Tanzania",
    country_code: "TZ",
    long_slug: "tanzania",
    name: "Tanzania",
    name_chinese: "坦桑尼亚",
    overall_score: 3.04,
    region: "Africa",
    short_slug: "tanzania",
    slug: "tanzania",
  },
  TH: {
    cost_score: 5,
    country: "Thailand",
    country_code: "TH",
    long_slug: "thailand",
    name: "Thailand",
    name_chinese: "泰国",
    overall_score: 3.55,
    region: "Asia",
    short_slug: "thailand",
    slug: "thailand",
  },
  TL: {
    cost_score: 4.71,
    country: "Timor Leste",
    country_code: "TL",
    long_slug: "timor-leste",
    name: "Timor Leste",
    name_chinese: "东帝汶",
    overall_score: 3.18,
    region: "Asia",
    short_slug: "timor-leste",
    slug: "timor-leste",
  },
  TG: {
    cost_score: 5,
    country: "Togo",
    country_code: "TG",
    long_slug: "togo",
    name: "Togo",
    name_chinese: "多哥",
    overall_score: 3.2,
    region: "Africa",
    short_slug: "togo",
    slug: "togo",
  },
  TO: {
    cost_score: 4.62,
    country: "Tonga",
    country_code: "TO",
    long_slug: "tonga",
    name: "Tonga",
    name_chinese: "汤加",
    overall_score: 3.46,
    region: "Oceania",
    short_slug: "tonga",
    slug: "tonga",
  },
  TT: {
    cost_score: 4.49,
    country: "Trinidad and Tobago",
    country_code: "TT",
    long_slug: "trinidad-and-tobago",
    name: "Trinidad and Tobago",
    name_chinese: "特立尼达和多巴哥",
    overall_score: 3.29,
    region: "North America",
    short_slug: "trinidad-and-tobago",
    slug: "trinidad-and-tobago",
  },
  TN: {
    cost_score: 5,
    country: "Tunisia",
    country_code: "TN",
    long_slug: "tunisia",
    name: "Tunisia",
    name_chinese: "突尼斯",
    overall_score: 2.96,
    region: "Africa",
    short_slug: "tunisia",
    slug: "tunisia",
  },
  TR: {
    cost_score: 5,
    country: "Turkey",
    country_code: "TR",
    long_slug: "turkey",
    name: "Turkey",
    name_chinese: "土耳其",
    overall_score: 3.43,
    region: "Europe",
    short_slug: "turkey",
    slug: "turkey",
  },
  TM: {
    cost_score: 2.44,
    country: "Turkmenistan",
    country_code: "TM",
    long_slug: "turkmenistan",
    name: "Turkmenistan",
    name_chinese: "土库曼斯坦",
    overall_score: 2.78,
    region: "Asia",
    short_slug: "turkmenistan",
    slug: "turkmenistan",
  },
  TV: {
    cost_score: 3.15,
    country: "Tuvalu",
    country_code: "TV",
    long_slug: "tuvalu",
    name: "Tuvalu",
    name_chinese: "图瓦卢",
    overall_score: 2.87,
    region: "Oceania",
    short_slug: "tuvalu",
    slug: "tuvalu",
  },
  UG: {
    cost_score: 5,
    country: "Uganda",
    country_code: "UG",
    long_slug: "uganda",
    name: "Uganda",
    name_chinese: "乌干达",
    overall_score: 3.19,
    region: "Africa",
    short_slug: "uganda",
    slug: "uganda",
  },
  UA: {
    cost_score: 5,
    country: "Ukraine",
    country_code: "UA",
    long_slug: "ukraine",
    name: "Ukraine",
    name_chinese: "乌克兰",
    overall_score: 3.28,
    region: "Europe",
    short_slug: "ukraine",
    slug: "ukraine",
  },
  AE: {
    cost_score: 3.05,
    country: "United Arab Emirates",
    country_code: "AE",
    long_slug: "united-arab-emirates",
    name: "United Arab Emirates",
    name_chinese: "阿拉伯联合酋长国",
    overall_score: 3.38,
    region: "Asia",
    short_slug: "united-arab-emirates",
    slug: "united-arab-emirates",
  },
  GB: {
    cost_score: 2.55,
    country: "United Kingdom",
    country_code: "UK",
    long_slug: "united-kingdom",
    name: "United Kingdom",
    name_chinese: "英国",
    overall_score: 3.34,
    region: "Europe",
    short_slug: "united-kingdom",
    slug: "united-kingdom",
  },
  US: {
    cost_score: 3.02,
    country: "United States",
    country_code: "US",
    long_slug: "united-states",
    name: "United States",
    name_chinese: "美国",
    overall_score: 3.33,
    region: "North America",
    short_slug: "united-states",
    slug: "united-states",
  },
  UY: {
    cost_score: 4.11,
    country: "Uruguay",
    country_code: "UY",
    long_slug: "uruguay",
    name: "Uruguay",
    name_chinese: "乌拉圭",
    overall_score: 3.07,
    region: "Latin America",
    short_slug: "uruguay",
    slug: "uruguay",
  },
  UZ: {
    cost_score: 5,
    country: "Uzbekistan",
    country_code: "UZ",
    long_slug: "uzbekistan",
    name: "Uzbekistan",
    name_chinese: "乌兹别克斯坦",
    overall_score: 2.87,
    region: "Asia",
    short_slug: "uzbekistan",
    slug: "uzbekistan",
  },
  VU: {
    cost_score: 2.88,
    country: "Vanuatu",
    country_code: "VU",
    long_slug: "vanuatu",
    name: "Vanuatu",
    name_chinese: "瓦努阿图",
    overall_score: 2.86,
    region: "Oceania",
    short_slug: "vanuatu",
    slug: "vanuatu",
  },
  VA: {
    cost_score: 1.83,
    country: "Vatican City",
    country_code: "VA",
    long_slug: "vatican-city",
    name: "Vatican City",
    name_chinese: "梵蒂冈城",
    overall_score: 2.61,
    region: "Europe",
    short_slug: "vatican-city",
    slug: "vatican-city",
  },
  VE: {
    cost_score: 4.84,
    country: "Venezuela",
    country_code: "VE",
    long_slug: "venezuela",
    name: "Venezuela",
    name_chinese: "委内瑞拉",
    overall_score: 3.09,
    region: "Latin America",
    short_slug: "venezuela",
    slug: "venezuela",
  },
  VN: {
    cost_score: 5,
    country: "Vietnam",
    country_code: "VN",
    long_slug: "vietnam",
    name: "Vietnam",
    name_chinese: "越南",
    overall_score: 3.46,
    region: "Asia",
    short_slug: "vietnam",
    slug: "vietnam",
  },
  VI: {
    cost_score: 1,
    country: "United States Virgin Islands",
    country_code: "VI",
    long_slug: "united-states-virgin-islands",
    name: "United States Virgin Islands",
    name_chinese: "美属维尔京群岛",
    overall_score: 2.65,
    region: "North America",
    short_slug: "united-states-virgin-islands",
    slug: "united-states-virgin-islands",
  },
  VG: {
    cost_score: 1,
    country: "British Virgin Islands",
    country_code: "VG",
    long_slug: "british-virgin-islands",
    name: "British Virgin Islands",
    name_chinese: "英属维尔京群岛",
    overall_score: 2.77,
    region: "North America",
    short_slug: "british-virgin-islands",
    slug: "british-virgin-islands",
  },
  EH: {
    cost_score: 4.97,
    country: "Western Sahara",
    country_code: "EH",
    long_slug: "western-sahara",
    name: "Western Sahara",
    name_chinese: "撒哈拉沙漠西部",
    overall_score: 2.95,
    region: "Africa",
    short_slug: "western-sahara",
    slug: "western-sahara",
  },
  YE: {
    cost_score: 4.75,
    country: "Yemen",
    country_code: "YE",
    long_slug: "yemen",
    name: "Yemen",
    name_chinese: "也门",
    overall_score: 2.93,
    region: "Asia",
    short_slug: "yemen",
    slug: "yemen",
  },
  ZM: {
    cost_score: 5,
    country: "Zambia",
    country_code: "ZM",
    long_slug: "zambia",
    name: "Zambia",
    name_chinese: "赞比亚",
    overall_score: 3.15,
    region: "Africa",
    short_slug: "zambia",
    slug: "zambia",
  },
  ZW: {
    cost_score: 4.35,
    country: "Zimbabwe",
    country_code: "ZW",
    long_slug: "zimbabwe",
    name: "Zimbabwe",
    name_chinese: "津巴布韦",
    overall_score: 3.51,
    region: "Africa",
    short_slug: "zimbabwe",
    slug: "zimbabwe",
  },
};
